In [1]:
import pandas as pd
import json

ModuleNotFoundError: No module named 'pandas'

In [146]:
# Ruta del archivo JSON
json_path = r'Dataset JSON/informacion general/arkham.json'

# Cargar el contenido del archivo JSON
with open(json_path, 'r') as file:
    json_data = json.load(file)

# Normalizar el JSON y crear un DataFrame
arkham = pd.json_normalize(json_data)


#eliminamos todas las columnas nulas o que sean iguales a 0
arkham = arkham.dropna(axis=1, how='all')
arkham = arkham.loc[:, (arkham != 0).any(axis=0)]

#Eliminamos todas las columnas que contengan la palabra "community", "market_data.ath", "description"
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='community')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='market_data.ath')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='description')))]

#Le cambiamos los nombres a las columnas que nos interesan "market_data.circulating_supply" y "market_data.circulating_supply"
arkham = arkham.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
arkham = arkham.rename(columns={'market_data.total_supply': 'total_supply'})
#Eliminamos las columnas que no nos interesan que contienen "market_data", "localization", "links", "image"
# ya que nos interesan
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='market_data')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='localization')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='links')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='image')))]

arkham

,id,symbol,name,asset_platform_id,categories,additional_notices,country_origin,contract_address,sentiment_votes_up_percentage,sentiment_votes_down_percentage,...,market_cap_rank,status_updates,last_updated,tickers,platforms.ethereum,detail_platforms.ethereum.decimal_place,detail_platforms.ethereum.contract_address,total_supply,circulating_supply,developer_data.last_4_weeks_commit_activity_series
0,arkham,arkm,Arkham,ethereum,"[Binance Launchpad, Ethereum Ecosystem]",[],,0x6e2a43be0b1d33b726f0ca3b8de60b3482b8b050,88.89,11.11,...,358,[],2023-08-10T20:09:53.032Z,"[{'base': 'ARKM', 'target': 'USDT', 'market': ...",0x6e2a43be0b1d33b726f0ca3b8de60b3482b8b050,18,0x6e2a43be0b1d33b726f0ca3b8de60b3482b8b050,1000000000,150000000,[]

In [147]:


# Ruta del archivo JSON
json_path_bitcoin = r'Dataset JSON/informacion general/bitcoin.json'

# Cargar el contenido del archivo JSON
with open(json_path_bitcoin, 'rb') as file:
    json_data_bitcoin = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_bitcoin = json.loads(json_data_bitcoin)

# Normalizar el JSON y crear un DataFrame
bitcoin = pd.json_normalize(json_dict_bitcoin)

# Eliminar columnas nulas o que sean iguales a 0
bitcoin = bitcoin.dropna(axis=1, how='all')
bitcoin = bitcoin.loc[:, (bitcoin != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='community')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='market_data.ath')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='description')))]

# Cambiar nombres de columnas
bitcoin = bitcoin.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
bitcoin = bitcoin.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='market_data')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='localization')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='links')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='image')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='developer_data')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='public_interest')))]
bitcoin

,id,symbol,name,block_time_in_minutes,hashing_algorithm,categories,additional_notices,country_origin,genesis_date,sentiment_votes_up_percentage,...,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,platforms.,detail_platforms..contract_address,total_supply,circulating_supply
0,bitcoin,btc,Bitcoin,10,SHA-256,"[Cryptocurrency, Layer 1 (L1)]",[],,2009-01-03,82.12,...,83.151,99.241,100.011,[],2023-08-10T04:18:21.445Z,"[{'base': 'BTC', 'target': 'USDT', 'market': {...",,,21000000,19452943

In [148]:
# Ruta del archivo JSON
json_path_bnb = r'Dataset JSON/informacion general/bnb.json'

# Cargar el contenido del archivo JSON
with open(json_path_bnb, 'rb') as file:
    json_data_bnb = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_bnb = json.loads(json_data_bnb)

# Normalizar el JSON y crear un DataFrame
bnb = pd.json_normalize(json_dict_bnb)

# Eliminar columnas nulas o que sean iguales a 0
bnb = bnb.dropna(axis=1, how='all')
bnb = bnb.loc[:, (bnb != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='community')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='market_data.ath')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='description')))]

# Cambiar nombres de columnas
bnb = bnb.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
bnb = bnb.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='market_data')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='localization')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='links')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='image')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='developer_data')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='public_interest')))]
bnb

,id,symbol,name,categories,additional_notices,country_origin,genesis_date,sentiment_votes_up_percentage,sentiment_votes_down_percentage,watchlist_portfolio_users,...,status_updates,last_updated,tickers,platforms.,platforms.ethereum,detail_platforms..contract_address,detail_platforms.ethereum.decimal_place,detail_platforms.ethereum.contract_address,total_supply,circulating_supply
0,binancecoin,bnb,BNB,"[Alleged SEC Securities, Smart Contract Platfo...",[],,2017-07-08,61.11,38.89,641529,...,"[{'description': 'Binance Black Friday - $100,...",2023-08-10T04:16:16.616Z,"[{'base': 'BNB', 'target': 'USDT', 'market': {...",,0xb8c77482e45f1f44de1745f52c74426c631bdd52,,18,0xb8c77482e45f1f44de1745f52c74426c631bdd52,153856150,153856150

In [149]:
# Ruta del archivo JSON
json_path_dogecoin = r'Dataset JSON/informacion general/dogecoin.json'

# Cargar el contenido del archivo JSON
with open(json_path_dogecoin, 'rb') as file:
    json_data_dogecoin = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_dogecoin = json.loads(json_data_dogecoin)

# Normalizar el JSON y crear un DataFrame
dogecoin = pd.json_normalize(json_dict_dogecoin)

# Eliminar columnas nulas o que sean iguales a 0
dogecoin = dogecoin.dropna(axis=1, how='all')
dogecoin = dogecoin.loc[:, (dogecoin != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='community')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='market_data.ath')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='description')))]

# Cambiar nombres de columnas
dogecoin = dogecoin.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
dogecoin = dogecoin.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='market_data')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='localization')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='links')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='image')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='developer_data')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='public_interest')))]
dogecoin

,id,symbol,name,block_time_in_minutes,hashing_algorithm,categories,additional_notices,country_origin,genesis_date,sentiment_votes_up_percentage,...,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,platforms.,detail_platforms..contract_address,total_supply,circulating_supply
0,dogecoin,doge,Dogecoin,1,Scrypt,"[Cryptocurrency, BNB Chain Ecosystem, Meme]",[],,2013-12-08,67.57,...,65.012,75.114,66.788,[],2023-08-10T04:22:37.907Z,"[{'base': 'DOGE', 'target': 'USDT', 'market': ...",,,1.405276e+11,1.405278e+11

In [150]:

# Ruta del archivo JSON
json_path_ethereum = r'Dataset JSON/informacion general/ethereum.json'

# Cargar el contenido del archivo JSON
with open(json_path_ethereum, 'rb') as file:
    json_data_ethereum = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_ethereum = json.loads(json_data_ethereum)

# Normalizar el JSON y crear un DataFrame
ethereum = pd.json_normalize(json_dict_ethereum)

# Eliminar columnas nulas o que sean iguales a 0
ethereum = ethereum.dropna(axis=1, how='all')
ethereum = ethereum.loc[:, (ethereum != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='community')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='market_data.ath')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='description')))]

# Cambiar nombres de columnas
ethereum = ethereum.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
ethereum = ethereum.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='market_data')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='localization')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='links')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='image')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='developer_data')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='public_interest')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='ico_data')))]
ethereum

,id,symbol,name,hashing_algorithm,categories,additional_notices,country_origin,genesis_date,sentiment_votes_up_percentage,sentiment_votes_down_percentage,...,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,platforms.,detail_platforms..contract_address,total_supply,circulating_supply
0,ethereum,eth,Ethereum,Ethash,"[Smart Contract Platform, Layer 1 (L1), Ethere...",[],,2015-07-30,67.27,32.73,...,78.783,97.494,95.183,[],2023-08-10T04:18:44.864Z,"[{'base': 'ETH', 'target': 'USDT', 'market': {...",,,1.201525e+08,1.201525e+08

In [151]:
# Ruta del archivo JSON
json_path_matic = r'Dataset JSON/informacion general/matic.json'

# Cargar el contenido del archivo JSON
with open(json_path_matic, 'rb') as file:
    json_data_matic = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_matic = json.loads(json_data_matic)

# Normalizar el JSON y crear un DataFrame
matic = pd.json_normalize(json_dict_matic)

# Eliminar columnas nulas o que sean iguales a 0
matic = matic.dropna(axis=1, how='all')
matic = matic.loc[:, (matic != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
matic = matic[matic.columns.drop(list(matic.filter(regex='community')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='market_data.ath')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='description')))]

# Cambiar nombres de columnas
matic = matic.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
matic = matic.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
matic = matic[matic.columns.drop(list(matic.filter(regex='market_data')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='localization')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='links')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='image')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='developer_data')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='public_interest')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='ico_data')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='detail_platforms')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='platforms')))]
matic

,id,symbol,name,asset_platform_id,categories,additional_notices,country_origin,contract_address,sentiment_votes_up_percentage,sentiment_votes_down_percentage,...,market_cap_rank,coingecko_rank,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,total_supply,circulating_supply
0,matic-network,matic,Polygon,ethereum,"[Binance Launchpad, Alleged SEC Securities, Ze...",[],IN,0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0,71.19,28.81,...,12,66,48.86,62.496,68.532,[],2023-08-10T20:16:34.640Z,"[{'base': 'MATIC', 'target': 'USDT', 'market':...",10000000000,9.319469e+09

In [152]:
# Ruta del archivo JSON
json_path_pepe = r'Dataset JSON/informacion general/pepe.json'

# Cargar el contenido del archivo JSON
with open(json_path_pepe, 'rb') as file:
    json_data_pepe = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_pepe = json.loads(json_data_pepe)

# Normalizar el JSON y crear un DataFrame
pepe = pd.json_normalize(json_dict_pepe)

# Eliminar columnas nulas o que sean iguales a 0
pepe = pepe.dropna(axis=1, how='all')
pepe = pepe.loc[:, (pepe != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='community')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='market_data.ath')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='description')))]

# Cambiar nombres de columnas
pepe = pepe.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
pepe = pepe.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='market_data')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='localization')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='links')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='image')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='developer_data')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='public_interest')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='ico_data')))]
pepe

,id,symbol,name,asset_platform_id,categories,additional_notices,country_origin,contract_address,sentiment_votes_up_percentage,sentiment_votes_down_percentage,...,platforms.binance-smart-chain,platforms.arbitrum-one,detail_platforms.ethereum.decimal_place,detail_platforms.ethereum.contract_address,detail_platforms.binance-smart-chain.decimal_place,detail_platforms.binance-smart-chain.contract_address,detail_platforms.arbitrum-one.decimal_place,detail_platforms.arbitrum-one.contract_address,total_supply,circulating_supply
0,pepe,pepe,Pepe,ethereum,"[Arbitrum Ecosystem, BNB Chain Ecosystem, Ethe...",[],,0x6982508145454ce325ddbe47a25d4ec3d2311933,76.54,23.46,...,0x25d887ce7a35172c62febfd67a1856f20faebb00,0x25d887ce7a35172c62febfd67a1856f20faebb00,18,0x6982508145454ce325ddbe47a25d4ec3d2311933,18,0x25d887ce7a35172c62febfd67a1856f20faebb00,18,0x25d887ce7a35172c62febfd67a1856f20faebb00,420690000000000,420690000000000

In [153]:

# Ruta del archivo JSON
json_path_usdt = r'Dataset JSON/informacion general/usdt.json'

# Cargar el contenido del archivo JSON
with open(json_path_usdt, 'rb') as file:
    json_data_usdt = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_usdt = json.loads(json_data_usdt)

# Normalizar el JSON y crear un DataFrame
usdt = pd.json_normalize(json_dict_usdt)

# Eliminar columnas nulas o que sean iguales a 0
usdt = usdt.dropna(axis=1, how='all')
usdt = usdt.loc[:, (usdt != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='community')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='market_data.ath')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='description')))]

# Cambiar nombres de columnas
usdt = usdt.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
usdt = usdt.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='market_data')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='localization')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='links')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='image')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='developer_data')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='public_interest')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='ico_data')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='platforms')))]
usdt

,id,symbol,name,asset_platform_id,categories,additional_notices,country_origin,contract_address,sentiment_votes_up_percentage,sentiment_votes_down_percentage,watchlist_portfolio_users,market_cap_rank,coingecko_rank,coingecko_score,liquidity_score,status_updates,last_updated,tickers,total_supply,circulating_supply
0,tether,usdt,Tether,ethereum,"[Mantle Ecosystem, Solana Ecosystem, Canto Eco...",[],,0xdac17f958d2ee523a2206206994597c13d831ec7,60,40,283004,3,150,41.416,101.651,[],2023-08-10T20:10:00.399Z,"[{'base': 'USDC', 'target': 'USDT', 'market': ...",8.353293e+10,8.353293e+10

In [154]:

# Ruta del archivo JSON
json_path_worldcoin = r'Dataset JSON/informacion general/worldcoin.json'

# Cargar el contenido del archivo JSON
with open(json_path_worldcoin, 'rb') as file:
    json_data_worldcoin = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_worldcoin = json.loads(json_data_worldcoin)

# Normalizar el JSON y crear un DataFrame
worldcoin = pd.json_normalize(json_dict_worldcoin)

# Eliminar columnas nulas o que sean iguales a 0
worldcoin = worldcoin.dropna(axis=1, how='all')
worldcoin = worldcoin.loc[:, (worldcoin != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='community')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='market_data.ath')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='description')))]

# Cambiar nombres de columnas
worldcoin = worldcoin.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
worldcoin = worldcoin.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='market_data')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='localization')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='links')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='image')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='developer_data')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='public_interest')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='ico_data')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='platforms')))]
worldcoin

,id,symbol,name,hashing_algorithm,categories,additional_notices,country_origin,genesis_date,watchlist_portfolio_users,market_cap_rank,coingecko_rank,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,total_supply,circulating_supply
0,worldcoin,wdc,WorldCoin,Scrypt,[],[],,2013-05-14,3582,3608,2686,11.995,26.498,1,[],2023-08-10T20:06:50.888Z,"[{'base': 'WDC', 'target': 'USDT', 'market': {...",265000000,18450

In [155]:

# Ruta del archivo JSON
json_path_xrp = r'Dataset JSON/informacion general/xrp.json'

# Cargar el contenido del archivo JSON
with open(json_path_xrp, 'rb') as file:
    json_data_xrp = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_xrp = json.loads(json_data_xrp)

# Normalizar el JSON y crear un DataFrame
xrp = pd.json_normalize(json_dict_xrp)

# Eliminar columnas nulas o que sean iguales a 0
xrp = xrp.dropna(axis=1, how='all')
xrp = xrp.loc[:, (xrp != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='community')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='market_data.ath')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='description')))]

# Cambiar nombres de columnas
xrp = xrp.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
xrp = xrp.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='market_data')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='localization')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='links')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='image')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='developer_data')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='public_interest')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='ico_data')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='platforms')))]
xrp

,id,symbol,name,categories,additional_notices,country_origin,sentiment_votes_up_percentage,sentiment_votes_down_percentage,watchlist_portfolio_users,market_cap_rank,coingecko_rank,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,total_supply,circulating_supply
0,ripple,xrp,XRP,[Cryptocurrency],[],,77.56,22.44,566466,5,3,66.223,83.005,81.07,[],2023-08-10T20:12:06.736Z,"[{'base': 'XRP', 'target': 'USDT', 'market': {...",99988519823,52787284454

In [156]:
#Ahora uniremos todos los dataframe por interseccion entre sus columnas
#Para ello usaremos la funcion merge de pandas

# Lista de los DataFrames que has creado
dataframes = [arkham, bnb, usdt, bitcoin, dogecoin, ethereum, matic, pepe, worldcoin, xrp]

# Concatenar los DataFrames
combined_crip = pd.concat(dataframes, ignore_index=True)
combined_crip = combined_crip[combined_crip.columns.drop(list(combined_crip.filter(regex='platform')))]

#volvemos a eliminar las columnas donde haya listas vacias o nulas
combined_crip = combined_crip.drop


#Convertimos combined_crip en un dataframe de pandas
combined_crip = pd.DataFrame(combined_crip)

ValueError: DataFrame constructor not properly called!

In [ ]:
#Cambiaremos los valores de "country_origin" donde sean nulos por "unknown"
#combined_crip['country_origin'] = combined_crip['country_origin'].replace('', 'Unknown')
combined_crip['country_origin']

TypeError: 'method' object is not subscriptable

In [ ]:
#lo pasamos a un archivo csv
combined_crip.to_csv('Informacion General.csv', index=False)

In [189]:
#Ahora leeremos las capitalizaciones y cotizaciones de las criptomonedas a lo largo del tiempo, para ello usaremos la API de CoinGecko tambien.
arkham_cap_json = r'Dataset JSON/capitalizacion y cotizacion/arkham.json'
bitcoin_cap_json = r'Dataset JSON/capitalizacion y cotizacion/bitcoin.json'
ethereum_cap_json = r'Dataset JSON/capitalizacion y cotizacion/ethereum.json'
dogecoin_cap_json = r'Dataset JSON/capitalizacion y cotizacion/dogecoin.json'
usdt_cap_json = r'Dataset JSON/capitalizacion y cotizacion/usdt.json'
xrp_cap_json = r'Dataset JSON/capitalizacion y cotizacion/xrp.json'
matic_cap_json = r'Dataset JSON/capitalizacion y cotizacion/matic.json'
worldcoin_cap_json = r'Dataset JSON/capitalizacion y cotizacion/worldcoin.json'
pepe_cap_json = r'Dataset JSON/capitalizacion y cotizacion/pepe.json'
bnb_cap_json = r'Dataset JSON/capitalizacion y cotizacion/bnb.json'

In [178]:
# Load the content of the JSON file
with open(arkham_cap_json, 'r') as file:
    arkham_cap_content = file.read()

# Convert the JSON string into a dictionary
arkham_cap = json.loads(arkham_cap_content)

# Normalize the JSON and create a DataFrame
arkham = pd.json_normalize(arkham_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = arkham_cap['prices']
prices_df_arkham = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna dia numero para poder hacer un plot de la evolucion de los precios y esta sera en funcion del indice de fila
prices_df_arkham['dia'] = prices_df_arkham.index
prices_df_arkham['capitalizacion propia'] = prices_df_arkham['prices'] * 120211068

       market_cap     price  dia
0   1689638400000  0.646829    0
1   1689724800000  0.646829    1
2   1689811200000  0.612542    2
3   1689897600000  0.586083    3
4   1689984000000  0.636433    4
5   1690070400000  0.622242    5
6   1690156800000  0.597445    6
7   1690243200000  0.530439    7
8   1690329600000  0.512679    8
9   1690416000000  0.543409    9
10  1690502400000  0.557870   10
11  1690588800000  0.541070   11
12  1690675200000  0.520037   12
13  1690761600000  0.505134   13
14  1690848000000  0.508447   14
15  1690934400000  0.506081   15
16  1691020800000  0.470809   16
17  1691107200000  0.459826   17
18  1691193600000  0.455571   18
19  1691280000000  0.423871   19
20  1691366400000  0.442911   20
21  1691452800000  0.421356   21
22  1691539200000  0.421502   22
23  1691625600000  0.424579   23
24  1691712000000  0.412053   24
25  1691783287000  0.418641   25

In [179]:

with open(bitcoin_cap_json, 'r') as file:
    bitcoin_cap_content = file.read()

# Convertir el JSON en un diccionario
bitcoin_cap = json.loads(bitcoin_cap_content)

# Normalize the JSON and create a DataFrame
bitcoin = pd.json_normalize(bitcoin_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = bitcoin_cap['prices']
prices_df_bitcoin = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_bitcoin['dia'] = prices_df_bitcoin.index
prices_df_bitcoin

         market_cap         price   dia
0     1367107200000    135.300000     0
1     1367193600000    141.960000     1
2     1367280000000    135.300000     2
3     1367366400000    117.000000     3
4     1367452800000    103.430000     4
...             ...           ...   ...
3752  1691452800000  29178.147752  3752
3753  1691539200000  29779.561671  3753
3754  1691625600000  29585.488077  3754
3755  1691712000000  29423.818916  3755
3756  1691765272000  29475.675912  3756

[3757 rows x 3 columns]

In [180]:
with open(bnb_cap_json, 'r') as file:
    bnb_cap_content = file.read()

# Convertir el JSON en un diccionario
bnb_cap = json.loads(bnb_cap_content)

# Normalize the JSON and create a DataFrame
bnb = pd.json_normalize(bnb_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = bnb_cap['prices']
prices_df_bnb = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_bnb['dia'] = prices_df_bnb.index
prices_df_bnb

         market_cap       price   dia
0     1505520000000    0.107251     0
1     1505606400000    0.154041     1
2     1505692800000    0.173491     2
3     1505779200000    0.168334     3
4     1505865600000    0.166628     4
...             ...         ...   ...
2150  1691452800000  241.738425  2150
2151  1691539200000  245.179427  2151
2152  1691625600000  244.010315  2152
2153  1691712000000  241.231912  2153
2154  1691748111000  240.123587  2154

[2155 rows x 3 columns]

In [182]:
with open(dogecoin_cap_json, 'r') as file:
    dogecoin_cap_content = file.read()

# Convertir el JSON en un diccionario
dogecoin_cap = json.loads(dogecoin_cap_content)

# Normalize the JSON and create a DataFrame
dogecoin = pd.json_normalize(dogecoin_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = dogecoin_cap['prices']
prices_df_dogecoin = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_dogecoin['dia'] = prices_df_dogecoin.index
prices_df_dogecoin

         market_cap     price   dia
0     1387065600000  0.000559     0
1     1387238400000  0.000218     1
2     1387324800000  0.000268     2
3     1387411200000  0.000475     3
4     1387497600000  0.000989     4
...             ...       ...   ...
3520  1691452800000  0.073374  3520
3521  1691539200000  0.075010  3521
3522  1691625600000  0.075385  3522
3523  1691712000000  0.075759  3523
3524  1691775448000  0.075336  3524

[3525 rows x 3 columns]

In [183]:
with open(ethereum_cap_json, 'r') as file:
    ethereum_cap_content = file.read()

# Convertir el JSON en un diccionario
ethereum_cap = json.loads(ethereum_cap_content)

# Normalize the JSON and create a DataFrame
ethereum = pd.json_normalize(ethereum_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = ethereum_cap['prices']
prices_df_ethereum = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_ethereum['dia'] = prices_df_ethereum.index
prices_df_ethereum

         market_cap        price   dia
0     1438905600000     2.831620     0
1     1438992000000     1.330750     1
2     1439164800000     0.687586     2
3     1439251200000     1.067379     3
4     1439337600000     1.256613     4
...             ...          ...   ...
2922  1691452800000  1826.933486  2922
2923  1691539200000  1856.844145  2923
2924  1691625600000  1855.890727  2924
2925  1691712000000  1850.876989  2925
2926  1691765019000  1852.552542  2926

[2927 rows x 3 columns]

In [184]:
with open(matic_cap_json, 'r') as file:
    matic_cap_content = file.read()

# Convertir el JSON en un diccionario
matic_cap = json.loads(matic_cap_content)

# Normalize the JSON and create a DataFrame
matic = pd.json_normalize(matic_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = matic_cap['prices']
prices_df_matic = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_matic['dia'] = prices_df_matic.index
prices_df_matic

         market_cap     price   dia
0     1556323200000  0.005470     0
1     1556409600000  0.005207     1
2     1556496000000  0.004381     2
3     1556582400000  0.003528     3
4     1556668800000  0.004396     4
...             ...       ...   ...
1564  1691452800000  0.664615  1564
1565  1691539200000  0.685845  1565
1566  1691625600000  0.690920  1566
1567  1691712000000  0.684658  1567
1568  1691781047000  0.677621  1568

[1569 rows x 3 columns]

In [185]:
with open(pepe_cap_json, 'r') as file:
    pepe_cap_content = file.read()

# Convertir el JSON en un diccionario
pepe_cap = json.loads(pepe_cap_content)

# Normalize the JSON and create a DataFrame
pepe = pd.json_normalize(pepe_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = pepe_cap['prices']
prices_df_pepe = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
# Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_pepe['dia'] = prices_df_pepe.index
prices_df_pepe

        market_cap         price  dia
0    1681776000000  1.901222e-07    0
1    1681862400000  1.901222e-07    1
2    1681948800000  2.487981e-07    2
3    1682035200000  3.043395e-07    3
4    1682121600000  1.993084e-07    4
..             ...           ...  ...
112  1691452800000  1.115301e-06  112
113  1691539200000  1.175549e-06  113
114  1691625600000  1.235447e-06  114
115  1691712000000  1.231541e-06  115
116  1691779941000  1.239864e-06  116

[117 rows x 3 columns]

In [186]:
with open(usdt_cap_json, 'r') as file:
    usdt_cap_content = file.read()

# Convertir el JSON en un diccionario
usdt_cap = json.loads(usdt_cap_content)

# Normalize the JSON and create a DataFrame
usdt = pd.json_normalize(usdt_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = usdt_cap['prices']
prices_df_usdt = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
# Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_usdt['dia'] = prices_df_usdt.index
prices_df_usdt

         market_cap     price   dia
0     1424822400000  1.210160     0
1     1425254400000  0.572521     1
2     1425600000000  1.000000     2
3     1425686400000  1.000000     3
4     1425772800000  1.000000     4
...             ...       ...   ...
3063  1691452800000  0.998873  3063
3064  1691539200000  0.999945  3064
3065  1691625600000  0.999712  3065
3066  1691712000000  0.998899  3066
3067  1691757000000  0.999052  3067

[3068 rows x 3 columns]

In [190]:
with open(worldcoin_cap_json, 'r') as file:
    worldcoin_cap_content = file.read()

# Convertir el JSON en un diccionario
worldcoin_cap = json.loads(worldcoin_cap_content)

# Normalize the JSON and create a DataFrame
worldcoin = pd.json_normalize(worldcoin_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = worldcoin_cap['prices']
prices_df_worldcoin = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
# Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_worldcoin['dia'] = prices_df_worldcoin.index
prices_df_worldcoin

        market_cap     price  dia
0    1690185643008  1.880894    0
1    1690189267734  2.691712    1
2    1690192834224  2.598011    2
3    1690196457202  2.623522    3
4    1690200070259  2.686059    4
..             ...       ...  ...
487  1691935229975  1.811863  487
488  1691938808289  1.801758  488
489  1691942455854  1.786274  489
490  1691946062106  1.814843  490
491  1691948516000  1.816201  491

[492 rows x 3 columns]

In [188]:
with open(xrp_cap_json, 'r') as file:
    xrp_cap_content = file.read()

# Convertir el JSON en un diccionario
xrp_cap = json.loads(xrp_cap_content)

# Normalize the JSON and create a DataFrame
xrp = pd.json_normalize(xrp_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = xrp_cap['prices']
prices_df_xrp = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
# Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_xrp['dia'] = prices_df_xrp.index
prices_df_xrp

         market_cap     price   dia
0     1375574400000  0.005874     0
1     1375660800000  0.005653     1
2     1375747200000  0.004669     2
3     1375833600000  0.004486     3
4     1375920000000  0.004196     4
...             ...       ...   ...
3651  1691452800000  0.620838  3651
3652  1691539200000  0.642624  3652
3653  1691625600000  0.643605  3653
3654  1691712000000  0.633214  3654
3655  1691768459000  0.629123  3655

[3656 rows x 3 columns]

In [193]:
#guardamos cada uno en un archivo csv en una carpeta llamada data
prices_df_arkham.to_csv('data/prices_df_arkham.csv', index=False)
prices_df_bitcoin.to_csv('data/prices_df_bitcoin.csv', index=False)
prices_df_bnb.to_csv('data/prices_df_bnb.csv', index=False)
prices_df_ethereum.to_csv('data/prices_df_ethereum.csv', index=False)
prices_df_dogecoin.to_csv('data/prices_df_dogecoin.csv', index=False)
prices_df_matic.to_csv('data/prices_df_matic.csv', index=False)
prices_df_pepe.to_csv('data/prices_df_pepe.csv', index=False)
prices_df_usdt.to_csv('data/prices_df_usdt.csv', index=False)
prices_df_worldcoin.to_csv('data/prices_df_worldcoin.csv', index=False)
prices_df_xrp.to_csv('data/prices_df_xrp.csv', index=False)