In [71]:
import pandas as pd
import json

In [72]:
# Ruta del archivo JSON
json_path = r'Dataset JSON/informacion general/arkham.json'

# Cargar el contenido del archivo JSON
with open(json_path, 'r') as file:
    json_data = json.load(file)

# Normalizar el JSON y crear un DataFrame
arkham = pd.json_normalize(json_data)


#eliminamos todas las columnas nulas o que sean iguales a 0
arkham = arkham.dropna(axis=1, how='all')
arkham = arkham.loc[:, (arkham != 0).any(axis=0)]

#Eliminamos todas las columnas que contengan la palabra "community", "market_data.ath", "description"
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='community')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='market_data.ath')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='description')))]

#Le cambiamos los nombres a las columnas que nos interesan "market_data.circulating_supply" y "market_data.circulating_supply"
arkham = arkham.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
arkham = arkham.rename(columns={'market_data.total_supply': 'total_supply'})
#Eliminamos las columnas que no nos interesan que contienen "market_data", "localization", "links", "image"
# ya que nos interesan
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='market_data')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='localization')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='links')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='image')))]

arkham

,id,symbol,name,asset_platform_id,categories,additional_notices,country_origin,contract_address,sentiment_votes_up_percentage,sentiment_votes_down_percentage,...,market_cap_rank,status_updates,last_updated,tickers,platforms.ethereum,detail_platforms.ethereum.decimal_place,detail_platforms.ethereum.contract_address,total_supply,circulating_supply,developer_data.last_4_weeks_commit_activity_series
0,arkham,arkm,Arkham,ethereum,"[Binance Launchpad, Ethereum Ecosystem]",[],,0x6e2a43be0b1d33b726f0ca3b8de60b3482b8b050,88.89,11.11,...,358,[],2023-08-10T20:09:53.032Z,"[{'base': 'ARKM', 'target': 'USDT', 'market': ...",0x6e2a43be0b1d33b726f0ca3b8de60b3482b8b050,18,0x6e2a43be0b1d33b726f0ca3b8de60b3482b8b050,1000000000,150000000,[]

In [73]:


# Ruta del archivo JSON
json_path_bitcoin = r'Dataset JSON/informacion general/bitcoin.json'

# Cargar el contenido del archivo JSON
with open(json_path_bitcoin, 'rb') as file:
    json_data_bitcoin = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_bitcoin = json.loads(json_data_bitcoin)

# Normalizar el JSON y crear un DataFrame
bitcoin = pd.json_normalize(json_dict_bitcoin)

# Eliminar columnas nulas o que sean iguales a 0
bitcoin = bitcoin.dropna(axis=1, how='all')
bitcoin = bitcoin.loc[:, (bitcoin != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='community')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='market_data.ath')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='description')))]

# Cambiar nombres de columnas
bitcoin = bitcoin.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
bitcoin = bitcoin.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='market_data')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='localization')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='links')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='image')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='developer_data')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='public_interest')))]
bitcoin

,id,symbol,name,block_time_in_minutes,hashing_algorithm,categories,additional_notices,country_origin,genesis_date,sentiment_votes_up_percentage,...,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,platforms.,detail_platforms..contract_address,total_supply,circulating_supply
0,bitcoin,btc,Bitcoin,10,SHA-256,"[Cryptocurrency, Layer 1 (L1)]",[],,2009-01-03,82.12,...,83.151,99.241,100.011,[],2023-08-10T04:18:21.445Z,"[{'base': 'BTC', 'target': 'USDT', 'market': {...",,,21000000,19452943

In [74]:
# Ruta del archivo JSON
json_path_bnb = r'Dataset JSON/informacion general/bnb.json'

# Cargar el contenido del archivo JSON
with open(json_path_bnb, 'rb') as file:
    json_data_bnb = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_bnb = json.loads(json_data_bnb)

# Normalizar el JSON y crear un DataFrame
bnb = pd.json_normalize(json_dict_bnb)

# Eliminar columnas nulas o que sean iguales a 0
bnb = bnb.dropna(axis=1, how='all')
bnb = bnb.loc[:, (bnb != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='community')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='market_data.ath')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='description')))]

# Cambiar nombres de columnas
bnb = bnb.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
bnb = bnb.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='market_data')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='localization')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='links')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='image')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='developer_data')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='public_interest')))]
bnb

,id,symbol,name,categories,additional_notices,country_origin,genesis_date,sentiment_votes_up_percentage,sentiment_votes_down_percentage,watchlist_portfolio_users,...,status_updates,last_updated,tickers,platforms.,platforms.ethereum,detail_platforms..contract_address,detail_platforms.ethereum.decimal_place,detail_platforms.ethereum.contract_address,total_supply,circulating_supply
0,binancecoin,bnb,BNB,"[Alleged SEC Securities, Smart Contract Platfo...",[],,2017-07-08,61.11,38.89,641529,...,"[{'description': 'Binance Black Friday - $100,...",2023-08-10T04:16:16.616Z,"[{'base': 'BNB', 'target': 'USDT', 'market': {...",,0xb8c77482e45f1f44de1745f52c74426c631bdd52,,18,0xb8c77482e45f1f44de1745f52c74426c631bdd52,153856150,153856150

In [75]:
# Ruta del archivo JSON
json_path_dogecoin = r'Dataset JSON/informacion general/dogecoin.json'

# Cargar el contenido del archivo JSON
with open(json_path_dogecoin, 'rb') as file:
    json_data_dogecoin = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_dogecoin = json.loads(json_data_dogecoin)

# Normalizar el JSON y crear un DataFrame
dogecoin = pd.json_normalize(json_dict_dogecoin)

# Eliminar columnas nulas o que sean iguales a 0
dogecoin = dogecoin.dropna(axis=1, how='all')
dogecoin = dogecoin.loc[:, (dogecoin != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='community')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='market_data.ath')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='description')))]

# Cambiar nombres de columnas
dogecoin = dogecoin.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
dogecoin = dogecoin.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='market_data')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='localization')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='links')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='image')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='developer_data')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='public_interest')))]
dogecoin

,id,symbol,name,block_time_in_minutes,hashing_algorithm,categories,additional_notices,country_origin,genesis_date,sentiment_votes_up_percentage,...,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,platforms.,detail_platforms..contract_address,total_supply,circulating_supply
0,dogecoin,doge,Dogecoin,1,Scrypt,"[Cryptocurrency, BNB Chain Ecosystem, Meme]",[],,2013-12-08,67.57,...,65.012,75.114,66.788,[],2023-08-10T04:22:37.907Z,"[{'base': 'DOGE', 'target': 'USDT', 'market': ...",,,1.405276e+11,1.405278e+11

In [76]:

# Ruta del archivo JSON
json_path_ethereum = r'Dataset JSON/informacion general/ethereum.json'

# Cargar el contenido del archivo JSON
with open(json_path_ethereum, 'rb') as file:
    json_data_ethereum = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_ethereum = json.loads(json_data_ethereum)

# Normalizar el JSON y crear un DataFrame
ethereum = pd.json_normalize(json_dict_ethereum)

# Eliminar columnas nulas o que sean iguales a 0
ethereum = ethereum.dropna(axis=1, how='all')
ethereum = ethereum.loc[:, (ethereum != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='community')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='market_data.ath')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='description')))]

# Cambiar nombres de columnas
ethereum = ethereum.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
ethereum = ethereum.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='market_data')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='localization')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='links')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='image')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='developer_data')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='public_interest')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='ico_data')))]
ethereum

,id,symbol,name,hashing_algorithm,categories,additional_notices,country_origin,genesis_date,sentiment_votes_up_percentage,sentiment_votes_down_percentage,...,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,platforms.,detail_platforms..contract_address,total_supply,circulating_supply
0,ethereum,eth,Ethereum,Ethash,"[Smart Contract Platform, Layer 1 (L1), Ethere...",[],,2015-07-30,67.27,32.73,...,78.783,97.494,95.183,[],2023-08-10T04:18:44.864Z,"[{'base': 'ETH', 'target': 'USDT', 'market': {...",,,1.201525e+08,1.201525e+08

In [77]:
# Ruta del archivo JSON
json_path_matic = r'Dataset JSON/informacion general/matic.json'

# Cargar el contenido del archivo JSON
with open(json_path_matic, 'rb') as file:
    json_data_matic = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_matic = json.loads(json_data_matic)

# Normalizar el JSON y crear un DataFrame
matic = pd.json_normalize(json_dict_matic)

# Eliminar columnas nulas o que sean iguales a 0
matic = matic.dropna(axis=1, how='all')
matic = matic.loc[:, (matic != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
matic = matic[matic.columns.drop(list(matic.filter(regex='community')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='market_data.ath')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='description')))]

# Cambiar nombres de columnas
matic = matic.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
matic = matic.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
matic = matic[matic.columns.drop(list(matic.filter(regex='market_data')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='localization')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='links')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='image')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='developer_data')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='public_interest')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='ico_data')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='detail_platforms')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='platforms')))]
matic

,id,symbol,name,asset_platform_id,categories,additional_notices,country_origin,contract_address,sentiment_votes_up_percentage,sentiment_votes_down_percentage,...,market_cap_rank,coingecko_rank,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,total_supply,circulating_supply
0,matic-network,matic,Polygon,ethereum,"[Binance Launchpad, Alleged SEC Securities, Ze...",[],IN,0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0,71.19,28.81,...,12,66,48.86,62.496,68.532,[],2023-08-10T20:16:34.640Z,"[{'base': 'MATIC', 'target': 'USDT', 'market':...",10000000000,9.319469e+09

In [78]:
# Ruta del archivo JSON
json_path_pepe = r'Dataset JSON/informacion general/pepe.json'

# Cargar el contenido del archivo JSON
with open(json_path_pepe, 'rb') as file:
    json_data_pepe = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_pepe = json.loads(json_data_pepe)

# Normalizar el JSON y crear un DataFrame
pepe = pd.json_normalize(json_dict_pepe)

# Eliminar columnas nulas o que sean iguales a 0
pepe = pepe.dropna(axis=1, how='all')
pepe = pepe.loc[:, (pepe != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='community')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='market_data.ath')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='description')))]

# Cambiar nombres de columnas
pepe = pepe.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
pepe = pepe.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='market_data')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='localization')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='links')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='image')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='developer_data')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='public_interest')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='ico_data')))]
pepe

,id,symbol,name,asset_platform_id,categories,additional_notices,country_origin,contract_address,sentiment_votes_up_percentage,sentiment_votes_down_percentage,...,platforms.binance-smart-chain,platforms.arbitrum-one,detail_platforms.ethereum.decimal_place,detail_platforms.ethereum.contract_address,detail_platforms.binance-smart-chain.decimal_place,detail_platforms.binance-smart-chain.contract_address,detail_platforms.arbitrum-one.decimal_place,detail_platforms.arbitrum-one.contract_address,total_supply,circulating_supply
0,pepe,pepe,Pepe,ethereum,"[Arbitrum Ecosystem, BNB Chain Ecosystem, Ethe...",[],,0x6982508145454ce325ddbe47a25d4ec3d2311933,76.54,23.46,...,0x25d887ce7a35172c62febfd67a1856f20faebb00,0x25d887ce7a35172c62febfd67a1856f20faebb00,18,0x6982508145454ce325ddbe47a25d4ec3d2311933,18,0x25d887ce7a35172c62febfd67a1856f20faebb00,18,0x25d887ce7a35172c62febfd67a1856f20faebb00,420690000000000,420690000000000

In [79]:

# Ruta del archivo JSON
json_path_usdt = r'Dataset JSON/informacion general/usdt.json'

# Cargar el contenido del archivo JSON
with open(json_path_usdt, 'rb') as file:
    json_data_usdt = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_usdt = json.loads(json_data_usdt)

# Normalizar el JSON y crear un DataFrame
usdt = pd.json_normalize(json_dict_usdt)

# Eliminar columnas nulas o que sean iguales a 0
usdt = usdt.dropna(axis=1, how='all')
usdt = usdt.loc[:, (usdt != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='community')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='market_data.ath')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='description')))]

# Cambiar nombres de columnas
usdt = usdt.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
usdt = usdt.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='market_data')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='localization')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='links')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='image')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='developer_data')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='public_interest')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='ico_data')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='platforms')))]
usdt

,id,symbol,name,asset_platform_id,categories,additional_notices,country_origin,contract_address,sentiment_votes_up_percentage,sentiment_votes_down_percentage,watchlist_portfolio_users,market_cap_rank,coingecko_rank,coingecko_score,liquidity_score,status_updates,last_updated,tickers,total_supply,circulating_supply
0,tether,usdt,Tether,ethereum,"[Mantle Ecosystem, Solana Ecosystem, Canto Eco...",[],,0xdac17f958d2ee523a2206206994597c13d831ec7,60,40,283004,3,150,41.416,101.651,[],2023-08-10T20:10:00.399Z,"[{'base': 'USDC', 'target': 'USDT', 'market': ...",8.353293e+10,8.353293e+10

In [80]:

# Ruta del archivo JSON
json_path_worldcoin = r'Dataset JSON/informacion general/worldcoin.json'

# Cargar el contenido del archivo JSON
with open(json_path_worldcoin, 'rb') as file:
    json_data_worldcoin = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_worldcoin = json.loads(json_data_worldcoin)

# Normalizar el JSON y crear un DataFrame
worldcoin = pd.json_normalize(json_dict_worldcoin)

# Eliminar columnas nulas o que sean iguales a 0
worldcoin = worldcoin.dropna(axis=1, how='all')
worldcoin = worldcoin.loc[:, (worldcoin != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='community')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='market_data.ath')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='description')))]

# Cambiar nombres de columnas
worldcoin = worldcoin.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
worldcoin = worldcoin.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='market_data')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='localization')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='links')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='image')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='developer_data')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='public_interest')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='ico_data')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='platforms')))]
worldcoin

,id,symbol,name,hashing_algorithm,categories,additional_notices,country_origin,genesis_date,watchlist_portfolio_users,market_cap_rank,coingecko_rank,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,total_supply,circulating_supply
0,worldcoin,wdc,WorldCoin,Scrypt,[],[],,2013-05-14,3582,3608,2686,11.995,26.498,1,[],2023-08-10T20:06:50.888Z,"[{'base': 'WDC', 'target': 'USDT', 'market': {...",265000000,18450

In [81]:

# Ruta del archivo JSON
json_path_xrp = r'Dataset JSON/informacion general/xrp.json'

# Cargar el contenido del archivo JSON
with open(json_path_xrp, 'rb') as file:
    json_data_xrp = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_xrp = json.loads(json_data_xrp)

# Normalizar el JSON y crear un DataFrame
xrp = pd.json_normalize(json_dict_xrp)

# Eliminar columnas nulas o que sean iguales a 0
xrp = xrp.dropna(axis=1, how='all')
xrp = xrp.loc[:, (xrp != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='community')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='market_data.ath')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='description')))]

# Cambiar nombres de columnas
xrp = xrp.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
xrp = xrp.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='market_data')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='localization')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='links')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='image')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='developer_data')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='public_interest')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='ico_data')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='platforms')))]
xrp

,id,symbol,name,categories,additional_notices,country_origin,sentiment_votes_up_percentage,sentiment_votes_down_percentage,watchlist_portfolio_users,market_cap_rank,coingecko_rank,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,total_supply,circulating_supply
0,ripple,xrp,XRP,[Cryptocurrency],[],,77.56,22.44,566466,5,3,66.223,83.005,81.07,[],2023-08-10T20:12:06.736Z,"[{'base': 'XRP', 'target': 'USDT', 'market': {...",99988519823,52787284454

In [82]:
#Ahora uniremos todos los dataframe por interseccion entre sus columnas
#Para ello usaremos la funcion merge de pandas

# Lista de los DataFrames que has creado
dataframes = [arkham, bnb, usdt, bitcoin, dogecoin, ethereum, matic, pepe, worldcoin, xrp]

# Concatenar los DataFrames
combined_crip = pd.concat(dataframes, ignore_index=True)
combined_crip = combined_crip[combined_crip.columns.drop(list(combined_crip.filter(regex='platform')))]

#volvemos a eliminar las columnas donde haya listas vacias o nulas
combined_crip = combined_crip.drop


#Convertimos combined_crip en un dataframe de pandas
combined_crip = pd.DataFrame(combined_crip)

ValueError: DataFrame constructor not properly called!

In [ ]:
#Cambiaremos los valores de "country_origin" donde sean nulos por "unknown"
combined_crip['country_origin'] = combined_crip['country_origin'].replace('', 'Unknown')
combined_crip['country_origin']

TypeError: 'method' object is not subscriptable

In [ ]:
#lo pasamos a un archivo csv
combined_crip.to_csv('Informacion General.csv', index=False)

In [83]:
#Ahora leeremos las capitalizaciones y cotizaciones de las criptomonedas a lo largo del tiempo, para ello usaremos la API de CoinGecko tambien.
arkham_cap_json = r'Dataset JSON/capitalizacion y cotizacion/arkham.json'
bitcoin_cap_json = r'Dataset JSON/capitalizacion y cotizacion/bitcoin.json'
ethereum_cap_json = r'Dataset JSON/capitalizacion y cotizacion/ethereum.json'
dogecoin_cap_json = r'Dataset JSON/capitalizacion y cotizacion/dogecoin.json'
usdt_cap_json = r'Dataset JSON/capitalizacion y cotizacion/usdt.json'
xrp_cap_json = r'Dataset JSON/capitalizacion y cotizacion/xrp.json'
matic_cap_json = r'Dataset JSON/capitalizacion y cotizacion/matic.json'
worldcoin_cap_json = r'Dataset JSON/capitalizacion y cotizacion/worldcoin.json'
pepe_cap_json = r'Dataset JSON/capitalizacion y cotizacion/pepe.json'
bnb_cap_json = r'Dataset JSON/capitalizacion y cotizacion/bnb.json'

In [89]:
# Load the content of the JSON file
with open(arkham_cap_json, 'r') as file:
    arkham_cap_content = file.read()

# Convert the JSON string into a dictionary
arkham_cap = json.loads(arkham_cap_content)

# Normalize the JSON and create a DataFrame
arkham = pd.json_normalize(arkham_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = arkham_cap['prices']
prices_df_arkham = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna dia numero para poder hacer un plot de la evolucion de los precios y esta sera en funcion del indice de fila
prices_df_arkham['dia'] = prices_df_arkham.index
#Dejamos las ultimas 30 filas para estudiar su comportamiento en el ultimo mes
prices_df_arkham30 = prices_df_arkham.tail(30)
#Reseteamos el indice
prices_df_arkham30 = prices_df_arkham30.reset_index(drop=True)
#convertimos el indice en la columna dia
prices_df_arkham30['dia'] = prices_df_arkham30.index + 1
prices_df_arkham30['cripto'] = 'Arkham'
prices_df_arkham30

       market_cap     price  dia  cripto
0   1690070400000  0.622242    1  Arkham
1   1690156800000  0.597445    2  Arkham
2   1690243200000  0.530439    3  Arkham
3   1690329600000  0.512679    4  Arkham
4   1690416000000  0.543409    5  Arkham
5   1690502400000  0.557870    6  Arkham
6   1690588800000  0.541070    7  Arkham
7   1690675200000  0.520037    8  Arkham
8   1690761600000  0.505134    9  Arkham
9   1690848000000  0.508447   10  Arkham
10  1690934400000  0.506081   11  Arkham
11  1691020800000  0.470809   12  Arkham
12  1691107200000  0.459826   13  Arkham
13  1691193600000  0.455571   14  Arkham
14  1691280000000  0.423871   15  Arkham
15  1691366400000  0.442911   16  Arkham
16  1691452800000  0.421356   17  Arkham
17  1691539200000  0.421502   18  Arkham
18  1691625600000  0.424579   19  Arkham
19  1691712000000  0.412053   20  Arkham
20  1691798400000  0.419833   21  Arkham
21  1691884800000  0.435984   22  Arkham
22  1691971200000  0.425877   23  Arkham
23  1692057600000  0.429669   24  Arkham
24  1692144000000  0.367175   25  Arkham
25  1692230400000  0.379371   26  Arkham
26  1692316800000  0.371846   27  Arkham
27  1692403200000  0.406836   28  Arkham
28  1692489600000  0.401661   29  Arkham
29  1692508219000  0.413009   30  Arkham

In [90]:

with open(bitcoin_cap_json, 'r') as file:
    bitcoin_cap_content = file.read()

# Convertir el JSON en un diccionario
bitcoin_cap = json.loads(bitcoin_cap_content)

# Normalize the JSON and create a DataFrame
bitcoin = pd.json_normalize(bitcoin_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = bitcoin_cap['prices']
prices_df_bitcoin = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_bitcoin['dia'] = prices_df_bitcoin.index
#Eliminamos las 30 ultimas filas 
prices_df_bitcoin30 = prices_df_bitcoin.tail(30)
#Reseteamos el indice
prices_df_bitcoin30 = prices_df_bitcoin30.reset_index(drop=True)
prices_df_bitcoin30['dia'] = prices_df_bitcoin30.index + 1
prices_df_bitcoin30['cripto'] = 'Bitcoin'
prices_df_bitcoin30

       market_cap         price  dia   cripto
0   1689292800000  31446.014971    1  Bitcoin
1   1689379200000  30311.827808    2  Bitcoin
2   1689465600000  30297.971400    3  Bitcoin
3   1689552000000  30237.334785    4  Bitcoin
4   1689638400000  30147.860079    5  Bitcoin
5   1689724800000  29848.032273    6  Bitcoin
6   1689811200000  29919.874838    7  Bitcoin
7   1689897600000  29787.041530    8  Bitcoin
8   1689984000000  29914.682728    9  Bitcoin
9   1690070400000  29710.155936   10  Bitcoin
10  1690156800000  30057.956719   11  Bitcoin
11  1690243200000  29184.901913   12  Bitcoin
12  1690329600000  29222.974630   13  Bitcoin
13  1690416000000  29363.672908   14  Bitcoin
14  1690502400000  29200.244001   15  Bitcoin
15  1690588800000  29314.097387   16  Bitcoin
16  1690675200000  29356.747746   17  Bitcoin
17  1690761600000  29277.755810   18  Bitcoin
18  1690848000000  29233.136366   19  Bitcoin
19  1690934400000  29537.109747   20  Bitcoin
20  1691020800000  29146.636271   21  Bitcoin
21  1691107200000  29176.150597   22  Bitcoin
22  1691193600000  29087.938086   23  Bitcoin
23  1691280000000  29046.800457   24  Bitcoin
24  1691366400000  29044.204376   25  Bitcoin
25  1691452800000  29178.147752   26  Bitcoin
26  1691539200000  29779.561671   27  Bitcoin
27  1691625600000  29585.488077   28  Bitcoin
28  1691712000000  29423.818916   29  Bitcoin
29  1691765272000  29475.675912   30  Bitcoin

In [93]:
with open(bnb_cap_json, 'r') as file:
    bnb_cap_content = file.read()

# Convertir el JSON en un diccionario
bnb_cap = json.loads(bnb_cap_content)

# Normalize the JSON and create a DataFrame
bnb = pd.json_normalize(bnb_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = bnb_cap['prices']
prices_df_bnb = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_bnb['dia'] = prices_df_bnb.index
#Dejamos las ultimas 30 filas
prices_df_bnb30 = prices_df_bnb.tail(30)
#Reseteamos el indice 
prices_df_bnb30 = prices_df_bnb30.reset_index(drop=True)
prices_df_bnb30['dia'] = prices_df_bnb30.index + 1
prices_df_bnb30['cripto'] = 'BNB'
prices_df_bnb30

       market_cap       price  dia cripto
0   1689292800000  255.788291    1    BNB
1   1689379200000  247.695854    2    BNB
2   1689465600000  251.092986    3    BNB
3   1689552000000  242.749491    4    BNB
4   1689638400000  244.197168    5    BNB
5   1689724800000  240.270930    6    BNB
6   1689811200000  241.332773    7    BNB
7   1689897600000  242.624777    8    BNB
8   1689984000000  243.768842    9    BNB
9   1690070400000  240.537852   10    BNB
10  1690156800000  242.381424   11    BNB
11  1690243200000  238.965494   12    BNB
12  1690329600000  237.730347   13    BNB
13  1690416000000  239.020092   14    BNB
14  1690502400000  240.417367   15    BNB
15  1690588800000  241.857825   16    BNB
16  1690675200000  242.556325   17    BNB
17  1690761600000  242.540332   18    BNB
18  1690848000000  241.193557   19    BNB
19  1690934400000  247.428737   20    BNB
20  1691020800000  240.379008   21    BNB
21  1691107200000  241.143787   22    BNB
22  1691193600000  241.492208   23    BNB
23  1691280000000  242.881970   24    BNB
24  1691366400000  242.574998   25    BNB
25  1691452800000  241.738425   26    BNB
26  1691539200000  245.179427   27    BNB
27  1691625600000  244.010315   28    BNB
28  1691712000000  241.231912   29    BNB
29  1691748111000  240.123587   30    BNB

In [97]:
with open(dogecoin_cap_json, 'r') as file:
    dogecoin_cap_content = file.read()

# Convertir el JSON en un diccionario
dogecoin_cap = json.loads(dogecoin_cap_content)

# Normalize the JSON and create a DataFrame
dogecoin = pd.json_normalize(dogecoin_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = dogecoin_cap['prices']
prices_df_dogecoin = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_dogecoin['dia'] = prices_df_dogecoin.index
#Dejamos los ultimos 30 días con el obetivo de monitorear el ultimo mes
prices_df_dogecoin30 = prices_df_dogecoin.tail(30)
#Reseteamos el indice y lo aplicamos sobre la columna dia
prices_df_dogecoin30.reset_index(inplace=True)
prices_df_dogecoin30['dia'] = prices_df_dogecoin30.index + 1
prices_df_dogecoin30['cripto'] = 'Dogecoin'
prices_df_dogecoin30 = prices_df_dogecoin30.drop(['index'], axis=1)
prices_df_dogecoin30

/var/folders/5r/4_p7m9h17bv8506l5bcbht940000gn/T/ipykernel_63729/404885360.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prices_df_dogecoin30['dia'] = prices_df_dogecoin30.index + 1
/var/folders/5r/4_p7m9h17bv8506l5bcbht940000gn/T/ipykernel_63729/404885360.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prices_df_dogecoin30['cripto'] = 'Dogecoin'

       market_cap     price  dia    cripto
0   1689292800000  0.070533    1  Dogecoin
1   1689379200000  0.068471    2  Dogecoin
2   1689465600000  0.072033    3  Dogecoin
3   1689552000000  0.069662    4  Dogecoin
4   1689638400000  0.069974    5  Dogecoin
5   1689724800000  0.068610    6  Dogecoin
6   1689811200000  0.070176    7  Dogecoin
7   1689897600000  0.070596    8  Dogecoin
8   1689984000000  0.073368    9  Dogecoin
9   1690070400000  0.070418   10  Dogecoin
10  1690156800000  0.071893   11  Dogecoin
11  1690243200000  0.074431   12  Dogecoin
12  1690329600000  0.081719   13  Dogecoin
13  1690416000000  0.077942   14  Dogecoin
14  1690502400000  0.077524   15  Dogecoin
15  1690588800000  0.077283   16  Dogecoin
16  1690675200000  0.080199   17  Dogecoin
17  1690761600000  0.078035   18  Dogecoin
18  1690848000000  0.077873   19  Dogecoin
19  1690934400000  0.077873   20  Dogecoin
20  1691020800000  0.074167   21  Dogecoin
21  1691107200000  0.073642   22  Dogecoin
22  1691193600000  0.073471   23  Dogecoin
23  1691280000000  0.075603   24  Dogecoin
24  1691366400000  0.074149   25  Dogecoin
25  1691452800000  0.073374   26  Dogecoin
26  1691539200000  0.075010   27  Dogecoin
27  1691625600000  0.075385   28  Dogecoin
28  1691712000000  0.075759   29  Dogecoin
29  1691775448000  0.075336   30  Dogecoin

In [99]:
with open(ethereum_cap_json, 'r') as file:
    ethereum_cap_content = file.read()

# Convertir el JSON en un diccionario
ethereum_cap = json.loads(ethereum_cap_content)

# Normalize the JSON and create a DataFrame
ethereum = pd.json_normalize(ethereum_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = ethereum_cap['prices']
prices_df_ethereum = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_ethereum['dia'] = prices_df_ethereum.index
#Dejamos las ultimas 30 filas
prices_df_ethereum30 = prices_df_ethereum.tail(30)
#Reseteamos los indices para que empiecen en 0
prices_df_ethereum30 = prices_df_ethereum30.reset_index(drop=True)
#y lo aplicamos a la columna dia 
prices_df_ethereum30['dia'] = prices_df_ethereum30.index + 1
prices_df_ethereum30['cripto'] = 'Ethereum'
prices_df_ethereum30

       market_cap        price  dia    cripto
0   1689292800000  2003.253616    1  Ethereum
1   1689379200000  1935.940241    2  Ethereum
2   1689465600000  1931.389384    3  Ethereum
3   1689552000000  1923.035990    4  Ethereum
4   1689638400000  1912.122836    5  Ethereum
5   1689724800000  1897.199113    6  Ethereum
6   1689811200000  1889.223806    7  Ethereum
7   1689897600000  1891.014505    8  Ethereum
8   1689984000000  1891.472403    9  Ethereum
9   1690070400000  1858.311196   10  Ethereum
10  1690156800000  1887.826981   11  Ethereum
11  1690243200000  1850.431151   12  Ethereum
12  1690329600000  1857.596593   13  Ethereum
13  1690416000000  1871.533106   14  Ethereum
14  1690502400000  1858.777021   15  Ethereum
15  1690588800000  1874.693995   16  Ethereum
16  1690675200000  1880.918077   17  Ethereum
17  1690761600000  1861.869910   18  Ethereum
18  1690848000000  1857.276196   19  Ethereum
19  1690934400000  1869.745109   20  Ethereum
20  1691020800000  1838.011952   21  Ethereum
21  1691107200000  1835.701303   22  Ethereum
22  1691193600000  1828.461194   23  Ethereum
23  1691280000000  1835.070578   24  Ethereum
24  1691366400000  1826.706779   25  Ethereum
25  1691452800000  1826.933486   26  Ethereum
26  1691539200000  1856.844145   27  Ethereum
27  1691625600000  1855.890727   28  Ethereum
28  1691712000000  1850.876989   29  Ethereum
29  1691765019000  1852.552542   30  Ethereum

In [100]:
with open(matic_cap_json, 'r') as file:
    matic_cap_content = file.read()

# Convertir el JSON en un diccionario
matic_cap = json.loads(matic_cap_content)

# Normalize the JSON and create a DataFrame
matic = pd.json_normalize(matic_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = matic_cap['prices']
prices_df_matic = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_matic['dia'] = prices_df_matic.index
#Dejamos las ultimas 30 filas
prices_df_matic30 = prices_df_matic.tail(30)
#Reseteamos los índices
prices_df_matic30 = prices_df_matic30.reset_index(drop=True)
prices_df_matic30['dia'] = prices_df_matic30.index + 1
prices_df_matic30['cripto'] = 'Matic'

In [101]:
with open(pepe_cap_json, 'r') as file:
    pepe_cap_content = file.read()

# Convertir el JSON en un diccionario
pepe_cap = json.loads(pepe_cap_content)

# Normalize the JSON and create a DataFrame
pepe = pd.json_normalize(pepe_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = pepe_cap['prices']
prices_df_pepe = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
# Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_pepe['dia'] = prices_df_pepe.index
#Nos quedamos con los ultimos 30 dias
prices_df_pepe30 = prices_df_pepe.tail(30)
#reseteamos el indice a 0 
prices_df_pepe30 = prices_df_pepe30.reset_index(drop=True)
prices_df_pepe30['dia'] = prices_df_pepe30.index + 1
prices_df_pepe30['cripto'] = 'Pepe'
prices_df_pepe30

       market_cap     price  dia cripto
0   1689292800000  0.000002    1   Pepe
1   1689379200000  0.000002    2   Pepe
2   1689465600000  0.000002    3   Pepe
3   1689552000000  0.000002    4   Pepe
4   1689638400000  0.000002    5   Pepe
5   1689724800000  0.000002    6   Pepe
6   1689811200000  0.000002    7   Pepe
7   1689897600000  0.000002    8   Pepe
8   1689984000000  0.000002    9   Pepe
9   1690070400000  0.000001   10   Pepe
10  1690156800000  0.000002   11   Pepe
11  1690243200000  0.000001   12   Pepe
12  1690329600000  0.000001   13   Pepe
13  1690416000000  0.000001   14   Pepe
14  1690502400000  0.000001   15   Pepe
15  1690588800000  0.000001   16   Pepe
16  1690675200000  0.000001   17   Pepe
17  1690761600000  0.000001   18   Pepe
18  1690848000000  0.000001   19   Pepe
19  1690934400000  0.000001   20   Pepe
20  1691020800000  0.000001   21   Pepe
21  1691107200000  0.000001   22   Pepe
22  1691193600000  0.000001   23   Pepe
23  1691280000000  0.000001   24   Pepe
24  1691366400000  0.000001   25   Pepe
25  1691452800000  0.000001   26   Pepe
26  1691539200000  0.000001   27   Pepe
27  1691625600000  0.000001   28   Pepe
28  1691712000000  0.000001   29   Pepe
29  1691779941000  0.000001   30   Pepe

In [102]:
with open(usdt_cap_json, 'r') as file:
    usdt_cap_content = file.read()

# Convertir el JSON en un diccionario
usdt_cap = json.loads(usdt_cap_content)

# Normalize the JSON and create a DataFrame
usdt = pd.json_normalize(usdt_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = usdt_cap['prices']
prices_df_usdt = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
# Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_usdt['dia'] = prices_df_usdt.index
#Nos quedamos con los últimos 30 días
prices_df_usdt30 = prices_df_usdt.tail(30)
#hacemos un index reset para que el index sea el número de fila
prices_df_usdt30.reset_index(drop=True, inplace=True)
prices_df_usdt30['dia'] = prices_df_usdt30.index + 1
prices_df_usdt30['cripto'] = 'USDT'
prices_df_usdt30

/var/folders/5r/4_p7m9h17bv8506l5bcbht940000gn/T/ipykernel_63729/3211257788.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prices_df_usdt30['dia'] = prices_df_usdt30.index + 1
/var/folders/5r/4_p7m9h17bv8506l5bcbht940000gn/T/ipykernel_63729/3211257788.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prices_df_usdt30['cripto'] = 'USDT'

       market_cap     price  dia cripto
0   1689292800000  1.000392    1   USDT
1   1689379200000  1.000707    2   USDT
2   1689465600000  1.000653    3   USDT
3   1689552000000  1.000548    4   USDT
4   1689638400000  0.999807    5   USDT
5   1689724800000  1.000481    6   USDT
6   1689811200000  1.000293    7   USDT
7   1689897600000  1.000199    8   USDT
8   1689984000000  1.000050    9   USDT
9   1690070400000  0.999749   10   USDT
10  1690156800000  0.999898   11   USDT
11  1690243200000  1.000097   12   USDT
12  1690329600000  0.999606   13   USDT
13  1690416000000  1.000833   14   USDT
14  1690502400000  0.999740   15   USDT
15  1690588800000  0.999945   16   USDT
16  1690675200000  0.999975   17   USDT
17  1690761600000  1.000238   18   USDT
18  1690848000000  0.999867   19   USDT
19  1690934400000  0.999942   20   USDT
20  1691020800000  0.999242   21   USDT
21  1691107200000  0.998680   22   USDT
22  1691193600000  0.998912   23   USDT
23  1691280000000  0.998987   24   USDT
24  1691366400000  0.998320   25   USDT
25  1691452800000  0.998873   26   USDT
26  1691539200000  0.999945   27   USDT
27  1691625600000  0.999712   28   USDT
28  1691712000000  0.998899   29   USDT
29  1691757000000  0.999052   30   USDT

In [103]:
with open(worldcoin_cap_json, 'r') as file:
    worldcoin_cap_content = file.read()

# Convertir el JSON en un diccionario
worldcoin_cap = json.loads(worldcoin_cap_content)

# Normalize the JSON and create a DataFrame
worldcoin = pd.json_normalize(worldcoin_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = worldcoin_cap['prices']
prices_df_worldcoin = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
# Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_worldcoin['dia'] = prices_df_worldcoin.index
#Nos quedaremos con los ultimos 30 dias
prices_df_worldcoin30 = prices_df_worldcoin.tail(30)
#Los reindexamos para que el plot empiece en 1
prices_df_worldcoin30 = prices_df_worldcoin30.reset_index(drop=True)
prices_df_worldcoin30['dia'] = prices_df_worldcoin30.index + 1
prices_df_worldcoin30['cripto'] = 'Worldcoin'
prices_df_worldcoin30

       market_cap     price  dia     cripto
0   1691845257599  1.787810    1  Worldcoin
1   1691848865353  1.769639    2  Worldcoin
2   1691852492569  1.771126    3  Worldcoin
3   1691856059202  1.774080    4  Worldcoin
4   1691859668535  1.769262    5  Worldcoin
5   1691863276273  1.771651    6  Worldcoin
6   1691866855572  1.749482    7  Worldcoin
7   1691870459764  1.758132    8  Worldcoin
8   1691874063830  1.749574    9  Worldcoin
9   1691877655575  1.752980   10  Worldcoin
10  1691881251383  1.762024   11  Worldcoin
11  1691884851761  1.757411   12  Worldcoin
12  1691888415952  1.771873   13  Worldcoin
13  1691892008506  1.788858   14  Worldcoin
14  1691895603904  1.800615   15  Worldcoin
15  1691899246400  1.797507   16  Worldcoin
16  1691902814891  1.803319   17  Worldcoin
17  1691906416094  1.804206   18  Worldcoin
18  1691910004119  1.811840   19  Worldcoin
19  1691913648718  1.803033   20  Worldcoin
20  1691917205377  1.819778   21  Worldcoin
21  1691920805551  1.796787   22  Worldcoin
22  1691924404353  1.806260   23  Worldcoin
23  1691928033962  1.800129   24  Worldcoin
24  1691931610807  1.798037   25  Worldcoin
25  1691935229975  1.811863   26  Worldcoin
26  1691938808289  1.801758   27  Worldcoin
27  1691942455854  1.786274   28  Worldcoin
28  1691946062106  1.814843   29  Worldcoin
29  1691948516000  1.816201   30  Worldcoin

In [104]:
with open(xrp_cap_json, 'r') as file:
    xrp_cap_content = file.read()

# Convertir el JSON en un diccionario
xrp_cap = json.loads(xrp_cap_content)

# Normalize the JSON and create a DataFrame
xrp = pd.json_normalize(xrp_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = xrp_cap['prices']
prices_df_xrp = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
# Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_xrp['dia'] = prices_df_xrp.index
#Dejasmos unicamente los 30 ultimos dias 
prices_df_xrp30 = prices_df_xrp.tail(30)
# y los re indexamos en la columna dia
prices_df_xrp30 = prices_df_xrp30.reset_index(drop=True)
prices_df_xrp30['dia'] = prices_df_xrp30.index=range(1,31)
prices_df_xrp30['cripto'] = 'XRP'
prices_df_xrp30

       market_cap     price  dia cripto
1   1689292800000  0.812509    1    XRP
2   1689379200000  0.719679    2    XRP
3   1689465600000  0.713256    3    XRP
4   1689552000000  0.747667    4    XRP
5   1689638400000  0.739496    5    XRP
6   1689724800000  0.781263    6    XRP
7   1689811200000  0.821237    7    XRP
8   1689897600000  0.793284    8    XRP
9   1689984000000  0.772681    9    XRP
10  1690070400000  0.731402   10    XRP
11  1690156800000  0.737991   11    XRP
12  1690243200000  0.703525   12    XRP
13  1690329600000  0.710253   13    XRP
14  1690416000000  0.715877   14    XRP
15  1690502400000  0.713436   15    XRP
16  1690588800000  0.712297   16    XRP
17  1690675200000  0.712607   17    XRP
18  1690761600000  0.704911   18    XRP
19  1690848000000  0.699030   19    XRP
20  1690934400000  0.707216   20    XRP
21  1691020800000  0.684740   21    XRP
22  1691107200000  0.664210   22    XRP
23  1691193600000  0.635810   23    XRP
24  1691280000000  0.628430   24    XRP
25  1691366400000  0.622153   25    XRP
26  1691452800000  0.620838   26    XRP
27  1691539200000  0.642624   27    XRP
28  1691625600000  0.643605   28    XRP
29  1691712000000  0.633214   29    XRP
30  1691768459000  0.629123   30    XRP

In [ ]:
capitalizaciones_json = r'Dataset JSON/capitalizaciones.json'
with open(capitalizaciones_json, 'r') as file:
    capitalizaciones_content = file.read()

# Convertir el JSON en un diccionario
capitalizaciones = json.loads(capitalizaciones_content)

# Normalize the JSON and create a DataFrame
capitalizaciones_df = pd.json_normalize(capitalizaciones)
capitalizaciones_df.head()

,data.active_cryptocurrencies,data.upcoming_icos,data.ongoing_icos,data.ended_icos,data.markets,data.total_market_cap.btc,data.total_market_cap.eth,data.total_market_cap.ltc,data.total_market_cap.bch,data.total_market_cap.bnb,...,data.market_cap_percentage.usdt,data.market_cap_percentage.bnb,data.market_cap_percentage.xrp,data.market_cap_percentage.usdc,data.market_cap_percentage.steth,data.market_cap_percentage.doge,data.market_cap_percentage.ada,data.market_cap_percentage.sol,data.market_cap_change_percentage_24h_usd,data.updated_at
0,10029,0,49,3376,800,4.140579e+07,6.609427e+08,1.456081e+10,5.131096e+09,5.034899e+09,...,6.819699,3.054559,2.745171,2.147863,1.212929,0.869776,0.860291,0.802846,-0.202186,1691641012

In [108]:
#Vamos a unir todos los dataframe por la columna dia y vamos a crear un nuevo dataframe con todos los datos
mesCrypto = pd.concat([prices_df_arkham30, prices_df_bitcoin30, prices_df_bnb30, prices_df_dogecoin30, prices_df_ethereum30, prices_df_matic30, prices_df_pepe30, prices_df_usdt30, prices_df_worldcoin30, prices_df_xrp30])
mesCrypto

       market_cap     price  dia  cripto
0   1690070400000  0.622242    1  Arkham
1   1690156800000  0.597445    2  Arkham
2   1690243200000  0.530439    3  Arkham
3   1690329600000  0.512679    4  Arkham
4   1690416000000  0.543409    5  Arkham
..            ...       ...  ...     ...
26  1691452800000  0.620838   26     XRP
27  1691539200000  0.642624   27     XRP
28  1691625600000  0.643605   28     XRP
29  1691712000000  0.633214   29     XRP
30  1691768459000  0.629123   30     XRP

[300 rows x 4 columns]

In [109]:
mesCrypto.to_csv('data/mesCrypto.csv', index=False)

In [ ]:
capitalizaciones_df.to_csv('data/capitalizaciones.csv', index=False)

In [ ]:
exchanges_json = r'Dataset JSON/Exchanges.json'
with open(exchanges_json, 'r') as file:
    exchanges_content = file.read()

# Convertir el JSON en un diccionario
exchanges = json.loads(exchanges_content)

# Normalize the JSON and create a DataFrame
exchanges_df = pd.json_normalize(exchanges)
exchanges_df

,id,name,year_established,country,description,url,image,has_trading_incentive,trust_score,trust_score_rank,trade_volume_24h_btc,trade_volume_24h_btc_normalized
0,binance,Binance,2017.0,Cayman Islands,,https://www.binance.com/,https://assets.coingecko.com/markets/images/52...,False,10,1,229556.844732,119740.672914
1,gdax,Coinbase Exchange,2012.0,United States,,https://coinbase-consumer.sjv.io/coingecko,https://assets.coingecko.com/markets/images/23...,False,10,2,24588.931022,24588.931022
2,bybit_spot,Bybit,2018.0,British Virgin Islands,Bybit is a cryptocurrency exchange that offers...,https://www.bybit.com,https://assets.coingecko.com/markets/images/69...,False,10,3,20688.844634,20688.844634
3,huobi,Huobi,2013.0,Seychelles,,https://www.huobi.com,https://assets.coingecko.com/markets/images/25...,False,10,4,30444.727245,18030.595783
4,kraken,Kraken,2011.0,United States,,https://r.kraken.com/c/2223866/687155/10583,https://assets.coingecko.com/markets/images/29...,False,10,5,15678.945338,11947.894646
...,...,...,...,...,...,...,...,...,...,...,...,...
95,bitazza,Bitazza,2021.0,Thailand,Bitazza is ASEAN's locally-based digital asset...,https://trade.bitazza.com/gl/exchange/,https://assets.coingecko.com/markets/images/83...,False,6,96,263.344021,263.344021
96,osmosis,Osmosis,2021.0,None,Osmosis is an automated market maker (AMM) pro...,https://app.osmosis.zone/,https://assets.coingecko.com/markets/images/68...,False,6,97,257.079716,257.079716
97,pulsex,PulseX,NaN,None,,https://app.pulsex.com/swap,https://assets.coingecko.com/markets/images/11...,False,6,98,234.571764,234.571764
98,gmo_japan,GMO Japan,NaN,Japan,,https://coin.z.com/jp/,https://assets.coingecko.com/markets/images/43...,False,6,99,228.362370,228.362370
99,kyberswap_elastic_arbitrum,Kyberswap Elastic (Arbitrum),NaN,None,,https://kyberswap.com/swap?networkId=42161,https://assets.coingecko.com/markets/images/96...,False,6,100,224.738199,224.738199

In [ ]:
exchanges_df.to_csv('data/exchanges.csv', index=False)