In [110]:
import pandas as pd
import json

In [146]:
# Ruta del archivo JSON
json_path = r'Dataset JSON/informacion general/arkham.json'

# Cargar el contenido del archivo JSON
with open(json_path, 'r') as file:
    json_data = json.load(file)

# Normalizar el JSON y crear un DataFrame
arkham = pd.json_normalize(json_data)


#eliminamos todas las columnas nulas o que sean iguales a 0
arkham = arkham.dropna(axis=1, how='all')
arkham = arkham.loc[:, (arkham != 0).any(axis=0)]

#Eliminamos todas las columnas que contengan la palabra "community", "market_data.ath", "description"
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='community')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='market_data.ath')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='description')))]

#Le cambiamos los nombres a las columnas que nos interesan "market_data.circulating_supply" y "market_data.circulating_supply"
arkham = arkham.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
arkham = arkham.rename(columns={'market_data.total_supply': 'total_supply'})
#Eliminamos las columnas que no nos interesan que contienen "market_data", "localization", "links", "image"
# ya que nos interesan
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='market_data')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='localization')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='links')))]
arkham = arkham[arkham.columns.drop(list(arkham.filter(regex='image')))]

arkham

,id,symbol,name,asset_platform_id,categories,additional_notices,country_origin,contract_address,sentiment_votes_up_percentage,sentiment_votes_down_percentage,...,market_cap_rank,status_updates,last_updated,tickers,platforms.ethereum,detail_platforms.ethereum.decimal_place,detail_platforms.ethereum.contract_address,total_supply,circulating_supply,developer_data.last_4_weeks_commit_activity_series
0,arkham,arkm,Arkham,ethereum,"[Binance Launchpad, Ethereum Ecosystem]",[],,0x6e2a43be0b1d33b726f0ca3b8de60b3482b8b050,88.89,11.11,...,358,[],2023-08-10T20:09:53.032Z,"[{'base': 'ARKM', 'target': 'USDT', 'market': ...",0x6e2a43be0b1d33b726f0ca3b8de60b3482b8b050,18,0x6e2a43be0b1d33b726f0ca3b8de60b3482b8b050,1000000000,150000000,[]

In [147]:


# Ruta del archivo JSON
json_path_bitcoin = r'Dataset JSON/informacion general/bitcoin.json'

# Cargar el contenido del archivo JSON
with open(json_path_bitcoin, 'rb') as file:
    json_data_bitcoin = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_bitcoin = json.loads(json_data_bitcoin)

# Normalizar el JSON y crear un DataFrame
bitcoin = pd.json_normalize(json_dict_bitcoin)

# Eliminar columnas nulas o que sean iguales a 0
bitcoin = bitcoin.dropna(axis=1, how='all')
bitcoin = bitcoin.loc[:, (bitcoin != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='community')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='market_data.ath')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='description')))]

# Cambiar nombres de columnas
bitcoin = bitcoin.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
bitcoin = bitcoin.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='market_data')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='localization')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='links')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='image')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='developer_data')))]
bitcoin = bitcoin[bitcoin.columns.drop(list(bitcoin.filter(regex='public_interest')))]
bitcoin

,id,symbol,name,block_time_in_minutes,hashing_algorithm,categories,additional_notices,country_origin,genesis_date,sentiment_votes_up_percentage,...,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,platforms.,detail_platforms..contract_address,total_supply,circulating_supply
0,bitcoin,btc,Bitcoin,10,SHA-256,"[Cryptocurrency, Layer 1 (L1)]",[],,2009-01-03,82.12,...,83.151,99.241,100.011,[],2023-08-10T04:18:21.445Z,"[{'base': 'BTC', 'target': 'USDT', 'market': {...",,,21000000,19452943

In [148]:
# Ruta del archivo JSON
json_path_bnb = r'Dataset JSON/informacion general/bnb.json'

# Cargar el contenido del archivo JSON
with open(json_path_bnb, 'rb') as file:
    json_data_bnb = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_bnb = json.loads(json_data_bnb)

# Normalizar el JSON y crear un DataFrame
bnb = pd.json_normalize(json_dict_bnb)

# Eliminar columnas nulas o que sean iguales a 0
bnb = bnb.dropna(axis=1, how='all')
bnb = bnb.loc[:, (bnb != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='community')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='market_data.ath')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='description')))]

# Cambiar nombres de columnas
bnb = bnb.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
bnb = bnb.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='market_data')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='localization')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='links')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='image')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='developer_data')))]
bnb = bnb[bnb.columns.drop(list(bnb.filter(regex='public_interest')))]
bnb

,id,symbol,name,categories,additional_notices,country_origin,genesis_date,sentiment_votes_up_percentage,sentiment_votes_down_percentage,watchlist_portfolio_users,...,status_updates,last_updated,tickers,platforms.,platforms.ethereum,detail_platforms..contract_address,detail_platforms.ethereum.decimal_place,detail_platforms.ethereum.contract_address,total_supply,circulating_supply
0,binancecoin,bnb,BNB,"[Alleged SEC Securities, Smart Contract Platfo...",[],,2017-07-08,61.11,38.89,641529,...,"[{'description': 'Binance Black Friday - $100,...",2023-08-10T04:16:16.616Z,"[{'base': 'BNB', 'target': 'USDT', 'market': {...",,0xb8c77482e45f1f44de1745f52c74426c631bdd52,,18,0xb8c77482e45f1f44de1745f52c74426c631bdd52,153856150,153856150

In [149]:
# Ruta del archivo JSON
json_path_dogecoin = r'Dataset JSON/informacion general/dogecoin.json'

# Cargar el contenido del archivo JSON
with open(json_path_dogecoin, 'rb') as file:
    json_data_dogecoin = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_dogecoin = json.loads(json_data_dogecoin)

# Normalizar el JSON y crear un DataFrame
dogecoin = pd.json_normalize(json_dict_dogecoin)

# Eliminar columnas nulas o que sean iguales a 0
dogecoin = dogecoin.dropna(axis=1, how='all')
dogecoin = dogecoin.loc[:, (dogecoin != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='community')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='market_data.ath')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='description')))]

# Cambiar nombres de columnas
dogecoin = dogecoin.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
dogecoin = dogecoin.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='market_data')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='localization')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='links')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='image')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='developer_data')))]
dogecoin = dogecoin[dogecoin.columns.drop(list(dogecoin.filter(regex='public_interest')))]
dogecoin

,id,symbol,name,block_time_in_minutes,hashing_algorithm,categories,additional_notices,country_origin,genesis_date,sentiment_votes_up_percentage,...,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,platforms.,detail_platforms..contract_address,total_supply,circulating_supply
0,dogecoin,doge,Dogecoin,1,Scrypt,"[Cryptocurrency, BNB Chain Ecosystem, Meme]",[],,2013-12-08,67.57,...,65.012,75.114,66.788,[],2023-08-10T04:22:37.907Z,"[{'base': 'DOGE', 'target': 'USDT', 'market': ...",,,1.405276e+11,1.405278e+11

In [150]:

# Ruta del archivo JSON
json_path_ethereum = r'Dataset JSON/informacion general/ethereum.json'

# Cargar el contenido del archivo JSON
with open(json_path_ethereum, 'rb') as file:
    json_data_ethereum = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_ethereum = json.loads(json_data_ethereum)

# Normalizar el JSON y crear un DataFrame
ethereum = pd.json_normalize(json_dict_ethereum)

# Eliminar columnas nulas o que sean iguales a 0
ethereum = ethereum.dropna(axis=1, how='all')
ethereum = ethereum.loc[:, (ethereum != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='community')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='market_data.ath')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='description')))]

# Cambiar nombres de columnas
ethereum = ethereum.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
ethereum = ethereum.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='market_data')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='localization')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='links')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='image')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='developer_data')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='public_interest')))]
ethereum = ethereum[ethereum.columns.drop(list(ethereum.filter(regex='ico_data')))]
ethereum

,id,symbol,name,hashing_algorithm,categories,additional_notices,country_origin,genesis_date,sentiment_votes_up_percentage,sentiment_votes_down_percentage,...,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,platforms.,detail_platforms..contract_address,total_supply,circulating_supply
0,ethereum,eth,Ethereum,Ethash,"[Smart Contract Platform, Layer 1 (L1), Ethere...",[],,2015-07-30,67.27,32.73,...,78.783,97.494,95.183,[],2023-08-10T04:18:44.864Z,"[{'base': 'ETH', 'target': 'USDT', 'market': {...",,,1.201525e+08,1.201525e+08

In [151]:
# Ruta del archivo JSON
json_path_matic = r'Dataset JSON/informacion general/matic.json'

# Cargar el contenido del archivo JSON
with open(json_path_matic, 'rb') as file:
    json_data_matic = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_matic = json.loads(json_data_matic)

# Normalizar el JSON y crear un DataFrame
matic = pd.json_normalize(json_dict_matic)

# Eliminar columnas nulas o que sean iguales a 0
matic = matic.dropna(axis=1, how='all')
matic = matic.loc[:, (matic != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
matic = matic[matic.columns.drop(list(matic.filter(regex='community')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='market_data.ath')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='description')))]

# Cambiar nombres de columnas
matic = matic.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
matic = matic.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
matic = matic[matic.columns.drop(list(matic.filter(regex='market_data')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='localization')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='links')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='image')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='developer_data')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='public_interest')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='ico_data')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='detail_platforms')))]
matic = matic[matic.columns.drop(list(matic.filter(regex='platforms')))]
matic

,id,symbol,name,asset_platform_id,categories,additional_notices,country_origin,contract_address,sentiment_votes_up_percentage,sentiment_votes_down_percentage,...,market_cap_rank,coingecko_rank,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,total_supply,circulating_supply
0,matic-network,matic,Polygon,ethereum,"[Binance Launchpad, Alleged SEC Securities, Ze...",[],IN,0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0,71.19,28.81,...,12,66,48.86,62.496,68.532,[],2023-08-10T20:16:34.640Z,"[{'base': 'MATIC', 'target': 'USDT', 'market':...",10000000000,9.319469e+09

In [152]:
# Ruta del archivo JSON
json_path_pepe = r'Dataset JSON/informacion general/pepe.json'

# Cargar el contenido del archivo JSON
with open(json_path_pepe, 'rb') as file:
    json_data_pepe = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_pepe = json.loads(json_data_pepe)

# Normalizar el JSON y crear un DataFrame
pepe = pd.json_normalize(json_dict_pepe)

# Eliminar columnas nulas o que sean iguales a 0
pepe = pepe.dropna(axis=1, how='all')
pepe = pepe.loc[:, (pepe != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='community')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='market_data.ath')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='description')))]

# Cambiar nombres de columnas
pepe = pepe.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
pepe = pepe.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='market_data')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='localization')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='links')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='image')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='developer_data')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='public_interest')))]
pepe = pepe[pepe.columns.drop(list(pepe.filter(regex='ico_data')))]
pepe

,id,symbol,name,asset_platform_id,categories,additional_notices,country_origin,contract_address,sentiment_votes_up_percentage,sentiment_votes_down_percentage,...,platforms.binance-smart-chain,platforms.arbitrum-one,detail_platforms.ethereum.decimal_place,detail_platforms.ethereum.contract_address,detail_platforms.binance-smart-chain.decimal_place,detail_platforms.binance-smart-chain.contract_address,detail_platforms.arbitrum-one.decimal_place,detail_platforms.arbitrum-one.contract_address,total_supply,circulating_supply
0,pepe,pepe,Pepe,ethereum,"[Arbitrum Ecosystem, BNB Chain Ecosystem, Ethe...",[],,0x6982508145454ce325ddbe47a25d4ec3d2311933,76.54,23.46,...,0x25d887ce7a35172c62febfd67a1856f20faebb00,0x25d887ce7a35172c62febfd67a1856f20faebb00,18,0x6982508145454ce325ddbe47a25d4ec3d2311933,18,0x25d887ce7a35172c62febfd67a1856f20faebb00,18,0x25d887ce7a35172c62febfd67a1856f20faebb00,420690000000000,420690000000000

In [153]:

# Ruta del archivo JSON
json_path_usdt = r'Dataset JSON/informacion general/usdt.json'

# Cargar el contenido del archivo JSON
with open(json_path_usdt, 'rb') as file:
    json_data_usdt = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_usdt = json.loads(json_data_usdt)

# Normalizar el JSON y crear un DataFrame
usdt = pd.json_normalize(json_dict_usdt)

# Eliminar columnas nulas o que sean iguales a 0
usdt = usdt.dropna(axis=1, how='all')
usdt = usdt.loc[:, (usdt != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='community')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='market_data.ath')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='description')))]

# Cambiar nombres de columnas
usdt = usdt.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
usdt = usdt.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='market_data')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='localization')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='links')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='image')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='developer_data')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='public_interest')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='ico_data')))]
usdt = usdt[usdt.columns.drop(list(usdt.filter(regex='platforms')))]
usdt

,id,symbol,name,asset_platform_id,categories,additional_notices,country_origin,contract_address,sentiment_votes_up_percentage,sentiment_votes_down_percentage,watchlist_portfolio_users,market_cap_rank,coingecko_rank,coingecko_score,liquidity_score,status_updates,last_updated,tickers,total_supply,circulating_supply
0,tether,usdt,Tether,ethereum,"[Mantle Ecosystem, Solana Ecosystem, Canto Eco...",[],,0xdac17f958d2ee523a2206206994597c13d831ec7,60,40,283004,3,150,41.416,101.651,[],2023-08-10T20:10:00.399Z,"[{'base': 'USDC', 'target': 'USDT', 'market': ...",8.353293e+10,8.353293e+10

In [154]:

# Ruta del archivo JSON
json_path_worldcoin = r'Dataset JSON/informacion general/worldcoin.json'

# Cargar el contenido del archivo JSON
with open(json_path_worldcoin, 'rb') as file:
    json_data_worldcoin = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_worldcoin = json.loads(json_data_worldcoin)

# Normalizar el JSON y crear un DataFrame
worldcoin = pd.json_normalize(json_dict_worldcoin)

# Eliminar columnas nulas o que sean iguales a 0
worldcoin = worldcoin.dropna(axis=1, how='all')
worldcoin = worldcoin.loc[:, (worldcoin != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='community')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='market_data.ath')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='description')))]

# Cambiar nombres de columnas
worldcoin = worldcoin.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
worldcoin = worldcoin.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='market_data')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='localization')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='links')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='image')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='developer_data')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='public_interest')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='ico_data')))]
worldcoin = worldcoin[worldcoin.columns.drop(list(worldcoin.filter(regex='platforms')))]
worldcoin

,id,symbol,name,hashing_algorithm,categories,additional_notices,country_origin,genesis_date,watchlist_portfolio_users,market_cap_rank,coingecko_rank,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,total_supply,circulating_supply
0,worldcoin,wdc,WorldCoin,Scrypt,[],[],,2013-05-14,3582,3608,2686,11.995,26.498,1,[],2023-08-10T20:06:50.888Z,"[{'base': 'WDC', 'target': 'USDT', 'market': {...",265000000,18450

In [155]:

# Ruta del archivo JSON
json_path_xrp = r'Dataset JSON/informacion general/xrp.json'

# Cargar el contenido del archivo JSON
with open(json_path_xrp, 'rb') as file:
    json_data_xrp = file.read().decode('utf-8')

# Convertir la cadena JSON en un diccionario
json_dict_xrp = json.loads(json_data_xrp)

# Normalizar el JSON y crear un DataFrame
xrp = pd.json_normalize(json_dict_xrp)

# Eliminar columnas nulas o que sean iguales a 0
xrp = xrp.dropna(axis=1, how='all')
xrp = xrp.loc[:, (xrp != 0).any(axis=0)]

# Eliminar columnas que contienen ciertas palabras clave
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='community')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='market_data.ath')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='description')))]

# Cambiar nombres de columnas
xrp = xrp.rename(columns={'market_data.circulating_supply': 'circulating_supply'})
xrp = xrp.rename(columns={'market_data.total_supply': 'total_supply'})

# Eliminar columnas no deseadas
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='market_data')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='localization')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='links')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='image')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='developer_data')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='public_interest')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='ico_data')))]
xrp = xrp[xrp.columns.drop(list(xrp.filter(regex='platforms')))]
xrp

,id,symbol,name,categories,additional_notices,country_origin,sentiment_votes_up_percentage,sentiment_votes_down_percentage,watchlist_portfolio_users,market_cap_rank,coingecko_rank,coingecko_score,developer_score,liquidity_score,status_updates,last_updated,tickers,total_supply,circulating_supply
0,ripple,xrp,XRP,[Cryptocurrency],[],,77.56,22.44,566466,5,3,66.223,83.005,81.07,[],2023-08-10T20:12:06.736Z,"[{'base': 'XRP', 'target': 'USDT', 'market': {...",99988519823,52787284454

In [156]:
#Ahora uniremos todos los dataframe por interseccion entre sus columnas
#Para ello usaremos la funcion merge de pandas

# Lista de los DataFrames que has creado
dataframes = [arkham, bnb, usdt, bitcoin, dogecoin, ethereum, matic, pepe, worldcoin, xrp]

# Concatenar los DataFrames
combined_crip = pd.concat(dataframes, ignore_index=True)
combined_crip = combined_crip[combined_crip.columns.drop(list(combined_crip.filter(regex='platform')))]

#volvemos a eliminar las columnas donde haya listas vacias o nulas
combined_crip = combined_crip.drop


#Convertimos combined_crip en un dataframe de pandas
combined_crip = pd.DataFrame(combined_crip)

ValueError: DataFrame constructor not properly called!

In [ ]:
#Cambiaremos los valores de "country_origin" donde sean nulos por "unknown"
#combined_crip['country_origin'] = combined_crip['country_origin'].replace('', 'Unknown')
combined_crip['country_origin']

TypeError: 'method' object is not subscriptable

In [ ]:
#lo pasamos a un archivo csv
combined_crip.to_csv('Informacion General.csv', index=False)

In [111]:
#Ahora leeremos las capitalizaciones y cotizaciones de las criptomonedas a lo largo del tiempo, para ello usaremos la API de CoinGecko tambien.
arkham_cap_json = r'Dataset JSON/capitalizacion y cotizacion/arkham.json'
bitcoin_cap_json = r'Dataset JSON/capitalizacion y cotizacion/bitcoin.json'
ethereum_cap_json = r'Dataset JSON/capitalizacion y cotizacion/ethereum.json'
dogecoin_cap_json = r'Dataset JSON/capitalizacion y cotizacion/dogecoin.json'
usdt_cap_json = r'Dataset JSON/capitalizacion y cotizacion/usdt.json'
xrp_cap_json = r'Dataset JSON/capitalizacion y cotizacion/xrp.json'
matic_cap_json = r'Dataset JSON/capitalizacion y cotizacion/matic.json'
worldcoin_cap_json = r'Dataset JSON/capitalizacion y cotizacion/worldcoin.json'
pepe_cap_json = r'Dataset JSON/capitalizacion y cotizacion/pepe.json'
bnb_cap_json = r'Dataset JSON/capitalizacion y cotizacion/bnb.json'

In [147]:
# Load the content of the JSON file
with open(arkham_cap_json, 'r') as file:
    arkham_cap_content = file.read()

# Convert the JSON string into a dictionary
arkham_cap = json.loads(arkham_cap_content)

# Normalize the JSON and create a DataFrame
arkham = pd.json_normalize(arkham_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = arkham_cap['prices']
prices_df_arkham = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna dia numero para poder hacer un plot de la evolucion de los precios y esta sera en funcion del indice de fila
prices_df_arkham['dia'] = prices_df_arkham.index
prices_df_arkham['capitalizacion propia'] = prices_df_arkham['price'] * 150268131
prices_df_arkham['capitalizacion propia'] = prices_df_arkham['capitalizacion propia'].astype(int)
prices_df_arkham = prices_df_arkham.tail(30)
prices_df_arkham = prices_df_arkham.reset_index(drop=True)
prices_df_arkham['dia'] = prices_df_arkham.index + 1
prices_df_arkham

       market_cap     price  dia  capitalizacion propia
0   1690070400000  0.622242    1               93503163
1   1690156800000  0.597445    2               89776997
2   1690243200000  0.530439    3               79708115
3   1690329600000  0.512679    4               77039306
4   1690416000000  0.543409    5               81656989
5   1690502400000  0.557870    6               83830090
6   1690588800000  0.541070    7               81305615
7   1690675200000  0.520037    8               78144923
8   1690761600000  0.505134    9               75905614
9   1690848000000  0.508447   10               76403429
10  1690934400000  0.506081   11               76047903
11  1691020800000  0.470809   12               70747601
12  1691107200000  0.459826   13               69097166
13  1691193600000  0.455571   14               68457848
14  1691280000000  0.423871   15               63694300
15  1691366400000  0.442911   16               66555373
16  1691452800000  0.421356   17               63316385
17  1691539200000  0.421502   18               63338370
18  1691625600000  0.424579   19               63800698
19  1691712000000  0.412053   20               61918400
20  1691798400000  0.419833   21               63087535
21  1691884800000  0.435984   22               65514483
22  1691971200000  0.425877   23               63995757
23  1692057600000  0.429669   24               64565503
24  1692144000000  0.367175   25               55174642
25  1692230400000  0.379371   26               57007396
26  1692316800000  0.371846   27               55876633
27  1692403200000  0.406836   28               61134435
28  1692489600000  0.401661   29               60356864
29  1692508219000  0.413009   30               62062125

In [146]:

with open(bitcoin_cap_json, 'r') as file:
    bitcoin_cap_content = file.read()

# Convertir el JSON en un diccionario
bitcoin_cap = json.loads(bitcoin_cap_content)

# Normalize the JSON and create a DataFrame
bitcoin = pd.json_normalize(bitcoin_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = bitcoin_cap['prices']
prices_df_bitcoin = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_bitcoin['dia'] = prices_df_bitcoin.index
prices_df_bitcoin['capitalizacion propia'] = prices_df_bitcoin['price'] * 19463025
prices_df_bitcoin['capitalizacion propia'] = prices_df_bitcoin['capitalizacion propia'].astype(int)
prices_df_bitcoin = prices_df_bitcoin.tail(30)
prices_df_bitcoin = prices_df_bitcoin.reset_index(drop=True)
prices_df_bitcoin['dia'] = prices_df_bitcoin.index + 1
prices_df_bitcoin

       market_cap         price  dia  capitalizacion propia
0   1689292800000  31446.014971    1           612034575532
1   1689379200000  30311.827808    2           589959862425
2   1689465600000  30297.971400    3           589690174809
3   1689552000000  30237.334785    4           588510002856
4   1689638400000  30147.860079    5           586768554418
5   1689724800000  29848.032273    6           580932998320
6   1689811200000  29919.874838    7           582331271973
7   1689897600000  29787.041530    8           579745933981
8   1689984000000  29914.682728    9           582230217809
9   1690070400000  29710.155936   10           578249507736
10  1690156800000  30057.956719   11           585018763065
11  1690243200000  29184.901913   12           568026475556
12  1690329600000  29222.974630   13           568767485805
13  1690416000000  29363.672908   14           571505899899
14  1690502400000  29200.244001   15           568325079003
15  1690588800000  29314.097387   16           570541010297
16  1690675200000  29356.747746   17           571371115297
17  1690761600000  29277.755810   18           569833693279
18  1690848000000  29233.136366   19           568965263911
19  1690934400000  29537.109747   20           574881505432
20  1691020800000  29146.636271   21           567281710405
21  1691107200000  29176.150597   22           567856148465
22  1691193600000  29087.938086   23           566139266166
23  1691280000000  29046.800457   24           565338603465
24  1691366400000  29044.204376   25           565288075866
25  1691452800000  29178.147752   26           567895019148
26  1691539200000  29779.561671   27           579600353296
27  1691625600000  29585.488077   28           575823094087
28  1691712000000  29423.818916   29           572676523157
29  1691765272000  29475.675912   30           573685817166

In [145]:
with open(bnb_cap_json, 'r') as file:
    bnb_cap_content = file.read()

# Convertir el JSON en un diccionario
bnb_cap = json.loads(bnb_cap_content)

# Normalize the JSON and create a DataFrame
bnb = pd.json_normalize(bnb_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = bnb_cap['prices']
prices_df_bnb = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_bnb['dia'] = prices_df_bnb.index
prices_df_bnb['capitalizacion propia'] = prices_df_bnb['price'] * 153851498
prices_df_bnb['capitalizacion propia'] = prices_df_bnb['capitalizacion propia'].astype(int)
prices_df_bnb = prices_df_bnb.tail(30)
prices_df_bnb = prices_df_bnb.reset_index(drop=True)
prices_df_bnb['dia'] = prices_df_bnb.index + 1
prices_df_bnb

       market_cap       price  dia  capitalizacion propia
0   1689292800000  255.788291    1            39353411814
1   1689379200000  247.695854    2            38108378227
2   1689465600000  251.092986    3            38631032106
3   1689552000000  242.749491    4            37347372892
4   1689638400000  244.197168    5            37570100084
5   1689724800000  240.270930    6            36966042575
6   1689811200000  241.332773    7            37129408626
7   1689897600000  242.624777    8            37328185423
8   1689984000000  243.768842    9            37504201491
9   1690070400000  240.537852   10            37007108897
10  1690156800000  242.381424   11            37290745236
11  1690243200000  238.965494   12            36765199291
12  1690329600000  237.730347   13            36575170041
13  1690416000000  239.020092   14            36773599162
14  1690502400000  240.417367   15            36988571995
15  1690588800000  241.857825   16            37210188753
16  1690675200000  242.556325   17            37317654012
17  1690761600000  242.540332   18            37315193356
18  1690848000000  241.193557   19            37107990046
19  1690934400000  247.428737   20            38067281762
20  1691020800000  240.379008   21            36982670408
21  1691107200000  241.143787   22            37100332933
22  1691193600000  241.492208   23            37153937888
23  1691280000000  242.881970   24            37367754923
24  1691366400000  242.574998   25            37320526828
25  1691452800000  241.738425   26            37191818756
26  1691539200000  245.179427   27            37721222198
27  1691625600000  244.010315   28            37541352463
28  1691712000000  241.231912   29            37113891013
29  1691748111000  240.123587   30            36943373582

In [144]:
with open(dogecoin_cap_json, 'r') as file:
    dogecoin_cap_content = file.read()

# Convertir el JSON en un diccionario
dogecoin_cap = json.loads(dogecoin_cap_content)

# Normalize the JSON and create a DataFrame
dogecoin = pd.json_normalize(dogecoin_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = dogecoin_cap['prices']
prices_df_dogecoin = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_dogecoin['dia'] = prices_df_dogecoin.index
prices_df_dogecoin['capitalizacion propia'] = prices_df_dogecoin['price'] * 140698136384
prices_df_dogecoin['capitalizacion propia'] = prices_df_dogecoin['capitalizacion propia'].astype(int)
prices_df_dogecoin = prices_df_dogecoin.tail(30)
prices_df_dogecoin = prices_df_dogecoin.reset_index(drop=True)
prices_df_dogecoin['dia'] = prices_df_dogecoin.index + 1
prices_df_dogecoin

       market_cap     price  dia  capitalizacion propia
0   1689292800000  0.070533    1             9923908326
1   1689379200000  0.068471    2             9633758782
2   1689465600000  0.072033    3            10134935205
3   1689552000000  0.069662    4             9801288422
4   1689638400000  0.069974    5             9845246697
5   1689724800000  0.068610    6             9653232743
6   1689811200000  0.070176    7             9873656508
7   1689897600000  0.070596    8             9932791375
8   1689984000000  0.073368    9            10322796409
9   1690070400000  0.070418   10             9907674712
10  1690156800000  0.071893   11            10115253160
11  1690243200000  0.074431   12            10472319023
12  1690329600000  0.081719   13            11497737885
13  1690416000000  0.077942   14            10966229671
14  1690502400000  0.077524   15            10907439407
15  1690588800000  0.077283   16            10873634531
16  1690675200000  0.080199   17            11283863946
17  1690761600000  0.078035   18            10979332769
18  1690848000000  0.077873   19            10956515796
19  1690934400000  0.077873   20            10956644752
20  1691020800000  0.074167   21            10435103855
21  1691107200000  0.073642   22            10361299330
22  1691193600000  0.073471   23            10337254096
23  1691280000000  0.075603   24            10637202661
24  1691366400000  0.074149   25            10432583889
25  1691452800000  0.073374   26            10323649609
26  1691539200000  0.075010   27            10553787104
27  1691625600000  0.075385   28            10606517471
28  1691712000000  0.075759   29            10659170774
29  1691775448000  0.075336   30            10599694397

In [143]:
with open(ethereum_cap_json, 'r') as file:
    ethereum_cap_content = file.read()

# Convertir el JSON en un diccionario
ethereum_cap = json.loads(ethereum_cap_content)

# Normalize the JSON and create a DataFrame
ethereum = pd.json_normalize(ethereum_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = ethereum_cap['prices']
prices_df_ethereum = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_ethereum['dia'] = prices_df_ethereum.index
prices_df_ethereum['capitalizacion propia'] = prices_df_ethereum['price'] * 120211068
prices_df_ethereum['capitalizacion propia'] = prices_df_ethereum['capitalizacion propia'].astype(int)
prices_df_ethereum = prices_df_ethereum.tail(30)
prices_df_ethereum = prices_df_ethereum.reset_index(drop=True)
prices_df_ethereum['dia'] = prices_df_ethereum.index + 1
prices_df_ethereum

       market_cap        price  dia  capitalizacion propia
0   1689292800000  2003.253616    1           240813256663
1   1689379200000  1935.940241    2           232721443924
2   1689465600000  1931.389384    3           232174380593
3   1689552000000  1923.035990    4           231170210138
4   1689638400000  1912.122836    5           229858328211
5   1689724800000  1897.199113    6           228064331539
6   1689811200000  1889.223806    7           227105611356
7   1689897600000  1891.014505    8           227320873304
8   1689984000000  1891.472403    9           227375917636
9   1690070400000  1858.311196   10           223389573524
10  1690156800000  1887.826981   11           226937697568
11  1690243200000  1850.431151   12           222442304872
12  1690329600000  1857.596593   13           223303670327
13  1690416000000  1871.533106   14           224978993434
14  1690502400000  1858.777021   15           223445570914
15  1690588800000  1874.693995   16           225358967321
16  1690675200000  1880.918077   17           226107170800
17  1690761600000  1861.869910   18           223817370333
18  1690848000000  1857.276196   19           223265155063
19  1690934400000  1869.745109   20           224764056400
20  1691020800000  1838.011952   21           220949379731
21  1691107200000  1835.701303   22           220671614123
22  1691193600000  1828.461194   23           219801272900
23  1691280000000  1835.070578   24           220595794017
24  1691366400000  1826.706779   25           219590372858
25  1691452800000  1826.933486   26           219617625465
26  1691539200000  1856.844145   27           223213217721
27  1691625600000  1855.890727   28           223098606423
28  1691712000000  1850.876989   29           222495899548
29  1691765019000  1852.552542   30           222697319582

In [142]:
with open(matic_cap_json, 'r') as file:
    matic_cap_content = file.read()

# Convertir el JSON en un diccionario
matic_cap = json.loads(matic_cap_content)

# Normalize the JSON and create a DataFrame
matic = pd.json_normalize(matic_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = matic_cap['prices']
prices_df_matic = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
#Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_matic['dia'] = prices_df_matic.index
prices_df_matic['capitalizacion propia'] = prices_df_matic['price'] * 9319469069
prices_df_matic['capitalizacion propia'] = prices_df_matic['capitalizacion propia'].astype(int)
prices_df_matic = prices_df_matic.tail(30)
prices_df_matic = prices_df_matic.reset_index(drop=True)
prices_df_matic['dia'] = prices_df_matic.index + 1
prices_df_matic

       market_cap     price  dia  capitalizacion propia
0   1689292800000  0.848912    1             7911406752
1   1689379200000  0.808997    2             7539421833
2   1689465600000  0.799175    3             7447888612
3   1689552000000  0.768094    4             7158230245
4   1689638400000  0.778668    5             7256772741
5   1689724800000  0.737500    6             6873104974
6   1689811200000  0.744695    7             6940161903
7   1689897600000  0.766161    8             7140213808
8   1689984000000  0.770982    9             7185141676
9   1690070400000  0.743669   10             6930596662
10  1690156800000  0.757537   11             7059840416
11  1690243200000  0.728412   12             6788408769
12  1690329600000  0.708470   13             6602559704
13  1690416000000  0.722021   14             6728852120
14  1690502400000  0.716060   15             6673301871
15  1690588800000  0.709453   16             6611722434
16  1690675200000  0.718811   17             6698934019
17  1690761600000  0.697725   18             6502422222
18  1690848000000  0.688207   19             6413727608
19  1690934400000  0.698898   20             6513354300
20  1691020800000  0.680097   21             6338141812
21  1691107200000  0.668413   22             6229250379
22  1691193600000  0.664277   23             6190707483
23  1691280000000  0.666194   24             6208577257
24  1691366400000  0.665654   25             6203539349
25  1691452800000  0.664615   26             6193858212
26  1691539200000  0.685845   27             6391712047
27  1691625600000  0.690920   28             6439009544
28  1691712000000  0.684658   29             6380653413
29  1691781047000  0.677621   30             6315071013

In [140]:
with open(pepe_cap_json, 'r') as file:
    pepe_cap_content = file.read()

# Convertir el JSON en un diccionario
pepe_cap = json.loads(pepe_cap_content)

# Normalize the JSON and create a DataFrame
pepe = pd.json_normalize(pepe_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = pepe_cap['prices']
prices_df_pepe = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
# Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_pepe['dia'] = prices_df_pepe.index
prices_df_pepe['capitalizacion propia'] = prices_df_pepe['price'] * 379790000000000
prices_df_pepe['capitalizacion propia'] = prices_df_pepe['capitalizacion propia'].astype(int)
prices_df_pepe = prices_df_pepe.tail(30)
prices_df_pepe = prices_df_pepe.reset_index(drop=True)
prices_df_pepe['dia'] = prices_df_pepe.index + 1
prices_df_pepe

In [139]:
with open(usdt_cap_json, 'r') as file:
    usdt_cap_content = file.read()

# Convertir el JSON en un diccionario
usdt_cap = json.loads(usdt_cap_content)

# Normalize the JSON and create a DataFrame
usdt = pd.json_normalize(usdt_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = usdt_cap['prices']
prices_df_usdt = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
# Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila

prices_df_usdt['capitalizacion propia'] = prices_df_usdt['price'] * 82853221628
prices_df_usdt['capitalizacion propia'] = prices_df_usdt['capitalizacion propia'].astype(int)
prices_df_usdt = prices_df_usdt.tail(30)
prices_df_usdt = prices_df_usdt.reset_index(drop=True)
prices_df_usdt['dia'] = prices_df_usdt.index + 1
prices_df_usdt

       market_cap     price  capitalizacion propia  dia
0   1689292800000  1.000392            82885667128    1
1   1689379200000  1.000707            82911768969    2
2   1689465600000  1.000653            82907332109    3
3   1689552000000  1.000548            82898648961    4
4   1689638400000  0.999807            82837246461    5
5   1689724800000  1.000481            82893070049    6
6   1689811200000  1.000293            82877487368    7
7   1689897600000  1.000199            82869731402    8
8   1689984000000  1.000050            82857395963    9
9   1690070400000  0.999749            82832429830   10
10  1690156800000  0.999898            82844804879   11
11  1690243200000  1.000097            82861285697   12
12  1690329600000  0.999606            82820599878   13
13  1690416000000  1.000833            82922205585   14
14  1690502400000  0.999740            82831644373   15
15  1690588800000  0.999945            82848696595   16
16  1690675200000  0.999975            82851111752   17
17  1690761600000  1.000238            82872927917   18
18  1690848000000  0.999867            82842188110   19
19  1690934400000  0.999942            82848382676   20
20  1691020800000  0.999242            82790411668   21
21  1691107200000  0.998680            82743843262   22
22  1691193600000  0.998912            82763118374   23
23  1691280000000  0.998987            82769285184   24
24  1691366400000  0.998320            82714015098   25
25  1691452800000  0.998873            82759858748   26
26  1691539200000  0.999945            82848705979   27
27  1691625600000  0.999712            82829360582   28
28  1691712000000  0.998899            82761998692   29
29  1691757000000  0.999052            82774710922   30

In [137]:
with open(worldcoin_cap_json, 'r') as file:
    worldcoin_cap_content = file.read()

# Convertir el JSON en un diccionario
worldcoin_cap = json.loads(worldcoin_cap_content)

# Normalize the JSON and create a DataFrame
worldcoin = pd.json_normalize(worldcoin_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = worldcoin_cap['prices']
prices_df_worldcoin = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
# Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila
prices_df_worldcoin['dia'] = prices_df_worldcoin.index
prices_df_worldcoin['capitalizacion propia'] = prices_df_worldcoin['price'] * 126706287
prices_df_worldcoin['capitalizacion propia'] = prices_df_worldcoin['capitalizacion propia'].astype(int)
prices_df_worldcoin = prices_df_worldcoin.tail(30)
prices_df_worldcoin = prices_df_worldcoin.reset_index(drop=True)
prices_df_worldcoin['dia'] = prices_df_worldcoin.index + 1

In [138]:
prices_df_worldcoin

       market_cap     price  dia  capitalizacion propia
0   1691845257599  1.787810    1              226526793
1   1691848865353  1.769639    2              224224368
2   1691852492569  1.771126    3              224412860
3   1691856059202  1.774080    4              224787037
4   1691859668535  1.769262    5              224176617
5   1691863276273  1.771651    6              224479264
6   1691866855572  1.749482    7              221670415
7   1691870459764  1.758132    8              222766356
8   1691874063830  1.749574    9              221682074
9   1691877655575  1.752980   10              222113579
10  1691881251383  1.762024   11              223259521
11  1691884851761  1.757411   12              222675005
12  1691888415952  1.771873   13              224507452
13  1691892008506  1.788858   14              226659551
14  1691895603904  1.800615   15              228149298
15  1691899246400  1.797507   16              227755485
16  1691902814891  1.803319   17              228491897
17  1691906416094  1.804206   18              228604255
18  1691910004119  1.811840   19              229571542
19  1691913648718  1.803033   20              228455629
20  1691917205377  1.819778   21              230577336
21  1691920805551  1.796787   22              227664257
22  1691924404353  1.806260   23              228864510
23  1691928033962  1.800129   24              228087628
24  1691931610807  1.798037   25              227822650
25  1691935229975  1.811863   26              229574456
26  1691938808289  1.801758   27              228294057
27  1691942455854  1.786274   28              226332136
28  1691946062106  1.814843   29              229951994
29  1691948516000  1.816201   30              230124127

In [136]:
with open(xrp_cap_json, 'r') as file:
    xrp_cap_content = file.read()

# Convertir el JSON en un diccionario
xrp_cap = json.loads(xrp_cap_content)

# Normalize the JSON and create a DataFrame
xrp = pd.json_normalize(xrp_cap)

# Convertir las listas anidadas en filas individuales para la columna 'prices'
prices_data = xrp_cap['prices']
prices_df_xrp = pd.DataFrame(prices_data, columns=['market_cap', 'price'])
# Haremos una columna día número para poder hacer un plot de la evolución de los precios y esta será en función del índice de fila

prices_df_xrp['capitalizacion propia'] = prices_df_xrp['price'] * 52841868447
prices_df_xrp['capitalizacion propia'] = prices_df_xrp['capitalizacion propia'].astype(int)
prices_df_xrp = prices_df_xrp.tail(30)
prices_df_xrp = prices_df_xrp.reset_index(drop=True)
prices_df_xrp['dia'] = prices_df_xrp.index + 1
prices_df_xrp

       market_cap     price  capitalizacion propia  dia
0   1689292800000  0.812509            42934513807    1
1   1689379200000  0.719679            38029203640    2
2   1689465600000  0.713256            37689758058    3
3   1689552000000  0.747667            39508127227    4
4   1689638400000  0.739496            39076361722    5
5   1689724800000  0.781263            41283401639    6
6   1689811200000  0.821237            43395681627    7
7   1689897600000  0.793284            41918589261    8
8   1689984000000  0.772681            40829900161    9
9   1690070400000  0.731402            38648626788   10
10  1690156800000  0.737991            38996827353   11
11  1690243200000  0.703525            37175596287   12
12  1690329600000  0.710253            37531083910   13
13  1690416000000  0.715877            37828304058   14
14  1690502400000  0.713436            37699279759   15
15  1690588800000  0.712297            37639082505   16
16  1690675200000  0.712607            37655493764   17
17  1690761600000  0.704911            37248819268   18
18  1690848000000  0.699030            36938066261   19
19  1690934400000  0.707216            37370588957   20
20  1691020800000  0.684740            36182926469   21
21  1691107200000  0.664210            35098119903   22
22  1691193600000  0.635810            33597391147   23
23  1691280000000  0.628430            33207427752   24
24  1691366400000  0.622153            32875739330   25
25  1691452800000  0.620838            32806237761   26
26  1691539200000  0.642624            33957463445   27
27  1691625600000  0.643605            34009301639   28
28  1691712000000  0.633214            33460202521   29
29  1691768459000  0.629123            33244009661   30

In [134]:
#guardamos cada uno en un archivo csv en una carpeta llamada data
prices_df_arkham.to_csv('data/prices_df_arkham.csv', index=False)
prices_df_bitcoin.to_csv('data/prices_df_bitcoin.csv', index=False)
prices_df_bnb.to_csv('data/prices_df_bnb.csv', index=False)
prices_df_ethereum.to_csv('data/prices_df_ethereum.csv', index=False)
prices_df_dogecoin.to_csv('data/prices_df_dogecoin.csv', index=False)
prices_df_matic.to_csv('data/prices_df_matic.csv', index=False)
prices_df_pepe.to_csv('data/prices_df_pepe.csv', index=False)
prices_df_usdt.to_csv('data/prices_df_usdt.csv', index=False)
prices_df_worldcoin.to_csv('data/prices_df_worldcoin.csv', index=False)
prices_df_xrp.to_csv('data/prices_df_xrp.csv', index=False)